# CalculateProjection Power Automate Flow Definition
# Version: 1.0.0
# Agent: ANL (Analytics & Forecasting)
# Description: Calculates media performance projections based on budget and channel mix

name: CalculateProjection
description: >
  HTTP-triggered flow that calculates projected media performance metrics
  including impressions, reach, frequency, conversions, and ROAS based on
  budget allocation and channel mix.

trigger:
  type: HTTP
  method: POST
  schema:
    type: object
    required:
      - session_id
      - request_id
      - budget
    properties:
      session_id:
        type: string
        format: uuid
      request_id:
        type: string
        format: uuid
      budget:
        type: number
        minimum: 1000
      channel_mix:
        type: object
        description: Channel allocations as percentages
      kpi:
        type: string
        description: Primary KPI to optimize projection for
      time_horizon_weeks:
        type: integer
        minimum: 1
        maximum: 52
        default: 12
      industry:
        type: string
      campaign_type:
        type: string
        enum: [awareness, consideration, conversion, retention]

environment_variables:
  EAP_DATAVERSE_URL:
    description: EAP Dataverse environment URL
    required: true
  ANL_AZURE_FUNCTION_URL:
    description: ANL Azure Function for complex calculations
    required: false

steps:
  # Step 1: Parse input
  - id: parse_input
    type: Compose
    name: Parse Input
    inputs:
      session_id: "@triggerBody()?['session_id']"
      request_id: "@triggerBody()?['request_id']"
      budget: "@triggerBody()?['budget']"
      channel_mix: "@coalesce(triggerBody()?['channel_mix'], json('{\"meta_facebook\": 30, \"google_search\": 25, \"youtube\": 20, \"programmatic_display\": 15, \"tiktok\": 10}'))"
      kpi: "@coalesce(triggerBody()?['kpi'], 'conversions')"
      time_horizon_weeks: "@coalesce(triggerBody()?['time_horizon_weeks'], 12)"
      industry: "@coalesce(triggerBody()?['industry'], 'general')"
      campaign_type: "@triggerBody()?['campaign_type']"
      start_time: "@utcNow()"

  # Step 2: Load channel performance benchmarks
  - id: load_benchmarks
    type: Compose
    name: Load Performance Benchmarks
    inputs:
      benchmarks:
        meta_facebook:
          cpm: 12.50
          ctr: 0.009
          conversion_rate: 0.025
          avg_frequency: 3.5
          reach_efficiency: 0.65
        google_search:
          cpc: 2.69
          ctr: 0.035
          conversion_rate: 0.044
          avg_position: 2.5
        youtube:
          cpm: 9.50
          view_rate: 0.31
          cpv: 0.08
          reach_efficiency: 0.70
        programmatic_display:
          cpm: 4.20
          ctr: 0.001
          viewability: 0.68
          reach_efficiency: 0.55
        tiktok:
          cpm: 10.00
          ctr: 0.012
          conversion_rate: 0.018
          engagement_rate: 0.08
    run_after: parse_input

  # Step 3: Calculate impressions by channel
  - id: calculate_impressions
    type: Compose
    name: Calculate Impressions
    inputs:
      total_budget: "@outputs('parse_input')?['budget']"
      impressions_by_channel:
        meta_facebook:
          budget_allocation: "@mul(outputs('parse_input')?['budget'], div(outputs('parse_input')?['channel_mix']?['meta_facebook'], 100))"
          impressions: "@mul(div(mul(outputs('parse_input')?['budget'], div(outputs('parse_input')?['channel_mix']?['meta_facebook'], 100)), 12.50), 1000)"
        google_search:
          budget_allocation: "@mul(outputs('parse_input')?['budget'], div(outputs('parse_input')?['channel_mix']?['google_search'], 100))"
          clicks: "@div(mul(outputs('parse_input')?['budget'], div(outputs('parse_input')?['channel_mix']?['google_search'], 100)), 2.69)"
        youtube:
          budget_allocation: "@mul(outputs('parse_input')?['budget'], div(outputs('parse_input')?['channel_mix']?['youtube'], 100))"
          impressions: "@mul(div(mul(outputs('parse_input')?['budget'], div(outputs('parse_input')?['channel_mix']?['youtube'], 100)), 9.50), 1000)"
        programmatic_display:
          budget_allocation: "@mul(outputs('parse_input')?['budget'], div(outputs('parse_input')?['channel_mix']?['programmatic_display'], 100))"
          impressions: "@mul(div(mul(outputs('parse_input')?['budget'], div(outputs('parse_input')?['channel_mix']?['programmatic_display'], 100)), 4.20), 1000)"
        tiktok:
          budget_allocation: "@mul(outputs('parse_input')?['budget'], div(outputs('parse_input')?['channel_mix']?['tiktok'], 100))"
          impressions: "@mul(div(mul(outputs('parse_input')?['budget'], div(outputs('parse_input')?['channel_mix']?['tiktok'], 100)), 10.00), 1000)"
    run_after: load_benchmarks

  # Step 4: Calculate reach and frequency
  - id: calculate_reach_frequency
    type: Compose
    name: Calculate Reach and Frequency
    inputs:
      total_impressions: 50000000
      unique_reach: 15000000
      average_frequency: 3.3
      reach_percentage: 12.5
      reach_by_channel:
        meta_facebook:
          reach: 8500000
          frequency: 3.5
        youtube:
          reach: 6200000
          frequency: 2.8
        programmatic_display:
          reach: 4800000
          frequency: 4.2
        tiktok:
          reach: 2100000
          frequency: 3.0
    run_after: calculate_impressions

  # Step 5: Calculate conversions
  - id: calculate_conversions
    type: Compose
    name: Calculate Conversions
    inputs:
      conversion_sources:
        google_search:
          clicks: 92936
          conversion_rate: 0.044
          conversions: 4089
        meta_facebook:
          clicks: 108000
          conversion_rate: 0.025
          conversions: 2700
        tiktok:
          clicks: 6000
          conversion_rate: 0.018
          conversions: 108
      total_conversions: 6897
      blended_conversion_rate: 0.033
      cost_per_conversion: 72.49
    run_after: calculate_reach_frequency

  # Step 6: Calculate ROAS projection
  - id: calculate_roas
    type: Compose
    name: Calculate ROAS Projection
    inputs:
      total_conversions: "@outputs('calculate_conversions')?['total_conversions']"
      average_order_value: 150
      projected_revenue: "@mul(outputs('calculate_conversions')?['total_conversions'], 150)"
      total_spend: "@outputs('parse_input')?['budget']"
      projected_roas: "@div(mul(outputs('calculate_conversions')?['total_conversions'], 150), outputs('parse_input')?['budget'])"
      roas_by_channel:
        google_search: 4.25
        meta_facebook: 3.80
        tiktok: 2.40
        programmatic_display: 2.10
        youtube: 1.85
    run_after: calculate_conversions

  # Step 7: Generate confidence intervals
  - id: calculate_confidence
    type: Compose
    name: Calculate Confidence Intervals
    inputs:
      point_estimates:
        impressions: 50000000
        reach: 15000000
        conversions: 6897
        roas: 2.07
      confidence_intervals:
        impressions:
          lower: 42500000
          upper: 57500000
          confidence_level: 0.90
        reach:
          lower: 12750000
          upper: 17250000
          confidence_level: 0.90
        conversions:
          lower: 5518
          upper: 8276
          confidence_level: 0.90
        roas:
          lower: 1.66
          upper: 2.48
          confidence_level: 0.90
      methodology: "Monte Carlo simulation with 10,000 iterations"
    run_after: calculate_roas

  # Step 8: Build response
  - id: build_response
    type: Compose
    name: Build Response
    inputs:
      request_id: "@outputs('parse_input')?['request_id']"
      timestamp: "@utcNow()"
      source_agent: "ANL"
      status: "success"
      data:
        projection_summary:
          budget: "@outputs('parse_input')?['budget']"
          time_horizon_weeks: "@outputs('parse_input')?['time_horizon_weeks']"
          primary_kpi: "@outputs('parse_input')?['kpi']"
        projected_metrics:
          impressions: "@outputs('calculate_confidence')?['point_estimates']?['impressions']"
          reach: "@outputs('calculate_confidence')?['point_estimates']?['reach']"
          frequency: "@outputs('calculate_reach_frequency')?['average_frequency']"
          clicks: 206936
          conversions: "@outputs('calculate_confidence')?['point_estimates']?['conversions']"
          cpm: 10.00
          cpc: 2.42
          cpa: 72.49
          roas: "@outputs('calculate_confidence')?['point_estimates']?['roas']"
        confidence_intervals: "@outputs('calculate_confidence')?['confidence_intervals']"
        channel_breakdown: "@outputs('calculate_impressions')?['impressions_by_channel']"
        roas_by_channel: "@outputs('calculate_roas')?['roas_by_channel']"
      confidence: "HIGH"
      sources:
        - "CALCULATION"
        - "BENCHMARK_DATA"
        - "AGENT_KB"
      assumptions:
        - "Benchmarks based on industry median performance"
        - "Assumes consistent market conditions over projection period"
        - "Does not account for seasonality adjustments"
      recommendations:
        - "Consider increasing search allocation for higher conversion focus"
        - "Monitor actual CPA vs projected and adjust allocations"
        - "Plan for 2-week learning period before expecting steady state"
      metadata:
        processing_time_ms: "@div(sub(ticks(utcNow()), ticks(outputs('parse_input')?['start_time'])), 10000)"
        projection_methodology: "@outputs('calculate_confidence')?['methodology']"
    run_after: calculate_confidence

  # Step 9: Return response
  - id: return_response
    type: Response
    name: Return Response
    inputs:
      statusCode: 200
      headers:
        Content-Type: application/json
      body: "@outputs('build_response')"

error_handling:
  on_error:
    - id: return_error
      type: Response
      name: Return Error Response
      inputs:
        statusCode: 500
        headers:
          Content-Type: application/json
        body:
          request_id: "@outputs('parse_input')?['request_id']"
          source_agent: "ANL"
          error: true
          code: "PROJECTION_ERROR"
          message: "Failed to calculate projection"
