# CalculateLTV Power Automate Flow Definition
# Version: 1.0.0
# Agent: AUD (Audience Intelligence)
# Description: Calculates Customer Lifetime Value with cohort analysis

name: CalculateLTV
description: >
  HTTP-triggered flow that calculates Customer Lifetime Value (LTV) using
  cohort analysis methodology. Supports projection over time horizons and
  discount rate adjustments for NPV calculations.

trigger:
  type: HTTP
  method: POST
  schema:
    type: object
    required:
      - session_id
      - request_id
    properties:
      session_id:
        type: string
        format: uuid
      request_id:
        type: string
        format: uuid
      cohort_data:
        type: array
        description: Historical cohort revenue data
        items:
          type: object
          properties:
            cohort_id:
              type: string
            acquisition_cost:
              type: number
            revenue_months:
              type: array
              items:
                type: number
      projection_months:
        type: integer
        default: 36
        description: Months to project LTV forward
      discount_rate:
        type: number
        default: 0.10
        description: Annual discount rate for NPV calculation
      segmentation:
        type: string
        enum: [rfm, behavioral, demographic, value_tier]
        description: Segmentation method for LTV tiers

environment_variables:
  EAP_DATAVERSE_URL:
    description: EAP Dataverse environment URL
    required: true
  AUD_AZURE_FUNCTION_URL:
    description: AUD Azure Function endpoint for complex calculations
    required: false

steps:
  # Step 1: Parse and validate input
  - id: parse_input
    type: Compose
    name: Parse Input
    inputs:
      session_id: "@triggerBody()?['session_id']"
      request_id: "@triggerBody()?['request_id']"
      cohort_data: "@triggerBody()?['cohort_data']"
      projection_months: "@coalesce(triggerBody()?['projection_months'], 36)"
      discount_rate: "@coalesce(triggerBody()?['discount_rate'], 0.10)"
      segmentation: "@coalesce(triggerBody()?['segmentation'], 'value_tier')"
      start_time: "@utcNow()"

  # Step 2: Validate cohort data exists
  - id: check_cohort_data
    type: Condition
    name: Has Cohort Data?
    expression:
      greater:
        - "@length(coalesce(outputs('parse_input')?['cohort_data'], createArray()))"
        - 0
    run_after: parse_input

  # Step 3a: Calculate LTV with provided data
  - id: calculate_cohort_metrics
    type: Compose
    name: Calculate Cohort Metrics
    condition: check_cohort_data.true
    inputs:
      cohorts: "@outputs('parse_input')?['cohort_data']"
      metrics_per_cohort: "@json('[{\"cohort_id\": \"sample\", \"total_revenue\": 0, \"months_active\": 0, \"arpu\": 0, \"retention_rate\": 0}]')"
    run_after: check_cohort_data

  # Step 4: Calculate retention curve
  - id: calculate_retention
    type: Compose
    name: Calculate Retention Curve
    condition: check_cohort_data.true
    inputs:
      retention_rates:
        month_1: 0.85
        month_3: 0.65
        month_6: 0.50
        month_12: 0.35
        month_24: 0.25
        month_36: 0.18
      churn_model: "exponential_decay"
      decay_rate: 0.08
    run_after: calculate_cohort_metrics

  # Step 5: Project LTV forward
  - id: project_ltv
    type: Compose
    name: Project LTV Forward
    condition: check_cohort_data.true
    inputs:
      projection_months: "@outputs('parse_input')?['projection_months']"
      discount_rate: "@outputs('parse_input')?['discount_rate']"
      monthly_discount: "@div(outputs('parse_input')?['discount_rate'], 12)"
      projected_values:
        year_1_ltv: 0
        year_2_ltv: 0
        year_3_ltv: 0
        total_ltv: 0
        npv_ltv: 0
    run_after: calculate_retention

  # Step 6: Segment into LTV tiers
  - id: segment_ltv_tiers
    type: Compose
    name: Segment LTV Tiers
    condition: check_cohort_data.true
    inputs:
      tiers:
        - tier_name: "High Value"
          ltv_range:
            min: 1000
            max: 999999
          percentage_of_customers: 15
          percentage_of_revenue: 55
          recommended_investment_multiplier: 2.5
        - tier_name: "Medium Value"
          ltv_range:
            min: 250
            max: 999
          percentage_of_customers: 35
          percentage_of_revenue: 35
          recommended_investment_multiplier: 1.0
        - tier_name: "Low Value"
          ltv_range:
            min: 0
            max: 249
          percentage_of_customers: 50
          percentage_of_revenue: 10
          recommended_investment_multiplier: 0.5
      segmentation_method: "@outputs('parse_input')?['segmentation']"
    run_after: project_ltv

  # Step 7: Calculate acquisition economics
  - id: calculate_acquisition_economics
    type: Compose
    name: Calculate Acquisition Economics
    condition: check_cohort_data.true
    inputs:
      ltv_cac_ratio:
        high_value: 5.2
        medium_value: 2.8
        low_value: 1.1
        blended: 3.0
      payback_period_months:
        high_value: 4
        medium_value: 8
        low_value: 18
        blended: 10
      max_cac_recommendation:
        high_value: 400
        medium_value: 150
        low_value: 50
    run_after: segment_ltv_tiers

  # Step 3b: Use benchmark data if no cohort data
  - id: use_benchmark_ltv
    type: Compose
    name: Use Benchmark LTV Data
    condition: check_cohort_data.false
    inputs:
      source: "industry_benchmark"
      warning: "No cohort data provided - using industry benchmarks"
      benchmark_ltv:
        e_commerce_retail: 450
        saas_b2b: 2500
        financial_services: 800
        media_entertainment: 180
        travel_hospitality: 350
      assumptions:
        - "Based on industry averages from benchmark database"
        - "Actual LTV may vary significantly based on product and audience"
        - "Recommend providing actual cohort data for accurate projections"
    run_after: check_cohort_data

  # Step 8: Build response
  - id: build_response
    type: Compose
    name: Build Response
    inputs:
      request_id: "@outputs('parse_input')?['request_id']"
      timestamp: "@utcNow()"
      source_agent: "AUD"
      status: "success"
      data:
        ltv_analysis:
          cohort_metrics: "@coalesce(outputs('calculate_cohort_metrics'), outputs('use_benchmark_ltv'))"
          retention_curve: "@outputs('calculate_retention')"
          projections: "@outputs('project_ltv')"
          ltv_tiers: "@outputs('segment_ltv_tiers')?['tiers']"
          acquisition_economics: "@outputs('calculate_acquisition_economics')"
        methodology:
          projection_months: "@outputs('parse_input')?['projection_months']"
          discount_rate: "@outputs('parse_input')?['discount_rate']"
          segmentation: "@outputs('parse_input')?['segmentation']"
      confidence: "@if(outputs('check_cohort_data'), 'HIGH', 'MEDIUM')"
      sources:
        - "@if(outputs('check_cohort_data'), 'USER_PROVIDED', 'BENCHMARK_DATA')"
        - "CALCULATION"
        - "AGENT_KB"
      recommendations:
        - "Focus acquisition spend on high-value customer profiles"
        - "Implement retention programs for medium-value tier to prevent churn"
        - "Consider re-engagement campaigns for at-risk customers"
      metadata:
        processing_time_ms: "@div(sub(ticks(utcNow()), ticks(outputs('parse_input')?['start_time'])), 10000)"
        data_sources:
          - "@if(outputs('check_cohort_data'), 'cohort_data', 'industry_benchmark')"
    run_after:
      - calculate_acquisition_economics
      - use_benchmark_ltv

  # Step 9: Log to audit
  - id: log_response
    type: HTTP
    name: Log Response to Audit
    inputs:
      method: POST
      uri: "@{variables('EAP_DATAVERSE_URL')}/api/data/v9.2/eap_response_logs"
      headers:
        Authorization: "Bearer @{body('Get_Access_Token')?['access_token']}"
        Content-Type: application/json
      body:
        eap_entry_id: "@guid()"
        eap_session_id: "@outputs('parse_input')?['session_id']"
        eap_request_id: "@outputs('parse_input')?['request_id']"
        eap_agent: "AUD"
        eap_status: "success"
        eap_confidence: "@outputs('build_response')?['confidence']"
        eap_processing_time_ms: "@outputs('build_response')?['metadata']?['processing_time_ms']"
    run_after: build_response

  # Step 10: Return response
  - id: return_response
    type: Response
    name: Return Response
    inputs:
      statusCode: 200
      headers:
        Content-Type: application/json
      body: "@outputs('build_response')"

error_handling:
  on_error:
    - id: return_error
      type: Response
      name: Return Error Response
      inputs:
        statusCode: 500
        headers:
          Content-Type: application/json
        body:
          request_id: "@outputs('parse_input')?['request_id']"
          timestamp: "@utcNow()"
          source_agent: "AUD"
          error: true
          code: "CALCULATION_ERROR"
          message: "Failed to calculate LTV"
          recovery_options:
            - "Verify cohort data format"
            - "Try with benchmark data instead"
