# SegmentAudience Power Automate Flow Definition
# Version: 1.0.0
# Agent: AUD (Audience Intelligence)
# Description: Segments audiences using RFM, behavioral, or demographic methods

name: SegmentAudience
description: >
  HTTP-triggered flow that segments audiences using various methodologies
  including RFM (Recency, Frequency, Monetary), behavioral clustering,
  and demographic profiling. Returns prioritized segments with sizing.

trigger:
  type: HTTP
  method: POST
  schema:
    type: object
    required:
      - session_id
      - request_id
      - segmentation_method
    properties:
      session_id:
        type: string
        format: uuid
      request_id:
        type: string
        format: uuid
      segmentation_method:
        type: string
        enum: [RFM, behavioral, demographic, custom]
      data_source:
        type: string
        enum: [1P, 2P, 3P, CDP, clean_room]
        default: 1P
      segment_count:
        type: integer
        minimum: 2
        maximum: 10
        default: 4
      constraints:
        type: object
        properties:
          minimum_segment_size:
            type: integer
          geographic_focus:
            type: array
            items:
              type: string
          exclude_segments:
            type: array
            items:
              type: string
      campaign_context:
        type: object
        properties:
          objective:
            type: string
          budget:
            type: number
          timeline_weeks:
            type: integer

environment_variables:
  EAP_DATAVERSE_URL:
    description: EAP Dataverse environment URL
    required: true

steps:
  # Step 1: Parse input
  - id: parse_input
    type: Compose
    name: Parse Input
    inputs:
      session_id: "@triggerBody()?['session_id']"
      request_id: "@triggerBody()?['request_id']"
      method: "@triggerBody()?['segmentation_method']"
      data_source: "@coalesce(triggerBody()?['data_source'], '1P')"
      segment_count: "@coalesce(triggerBody()?['segment_count'], 4)"
      constraints: "@triggerBody()?['constraints']"
      campaign_context: "@triggerBody()?['campaign_context']"
      start_time: "@utcNow()"

  # Step 2: Route by segmentation method
  - id: check_method
    type: Switch
    name: Route by Method
    expression: "@outputs('parse_input')?['method']"
    cases:
      RFM:
        - id: rfm_segmentation
          type: Compose
          name: RFM Segmentation
          inputs:
            method: "RFM"
            description: "Recency, Frequency, Monetary value segmentation"
            segments:
              - segment_id: "rfm_champions"
                segment_name: "Champions"
                rfm_scores:
                  recency: [4, 5]
                  frequency: [4, 5]
                  monetary: [4, 5]
                size_percentage: 10
                characteristics:
                  description: "Best customers - recent, frequent, high value"
                  behaviors: ["repeat_purchaser", "brand_advocate", "early_adopter"]
                  avg_order_value_index: 2.5
                  purchase_frequency_index: 3.0
                recommended_priority: "primary"
                recommended_tactics:
                  - "Loyalty rewards"
                  - "Exclusive early access"
                  - "Referral programs"
              - segment_id: "rfm_loyal"
                segment_name: "Loyal Customers"
                rfm_scores:
                  recency: [3, 4]
                  frequency: [4, 5]
                  monetary: [3, 4]
                size_percentage: 15
                characteristics:
                  description: "Consistent buyers with strong brand affinity"
                  behaviors: ["repeat_purchaser", "email_engaged"]
                  avg_order_value_index: 1.8
                  purchase_frequency_index: 2.5
                recommended_priority: "primary"
                recommended_tactics:
                  - "Cross-sell campaigns"
                  - "Subscription offers"
                  - "Personalized recommendations"
              - segment_id: "rfm_potential"
                segment_name: "Potential Loyalists"
                rfm_scores:
                  recency: [4, 5]
                  frequency: [2, 3]
                  monetary: [2, 3]
                size_percentage: 20
                characteristics:
                  description: "Recent customers with growth potential"
                  behaviors: ["recent_converter", "browser"]
                  avg_order_value_index: 1.2
                  purchase_frequency_index: 1.0
                recommended_priority: "secondary"
                recommended_tactics:
                  - "Onboarding sequences"
                  - "Second purchase incentives"
                  - "Category education"
              - segment_id: "rfm_at_risk"
                segment_name: "At Risk"
                rfm_scores:
                  recency: [1, 2]
                  frequency: [3, 4]
                  monetary: [3, 4]
                size_percentage: 15
                characteristics:
                  description: "Previously valuable customers showing churn signals"
                  behaviors: ["lapsed", "declining_engagement"]
                  avg_order_value_index: 1.5
                  purchase_frequency_index: 0.3
                recommended_priority: "secondary"
                recommended_tactics:
                  - "Win-back campaigns"
                  - "Exclusive re-engagement offers"
                  - "Feedback surveys"
              - segment_id: "rfm_hibernating"
                segment_name: "Hibernating"
                rfm_scores:
                  recency: [1, 2]
                  frequency: [1, 2]
                  monetary: [1, 2]
                size_percentage: 40
                characteristics:
                  description: "Inactive customers with low historical value"
                  behaviors: ["dormant", "one_time_buyer"]
                  avg_order_value_index: 0.5
                  purchase_frequency_index: 0.1
                recommended_priority: "tertiary"
                recommended_tactics:
                  - "Reactivation with strong offer"
                  - "Sunset email series"
                  - "Consider suppression"

      behavioral:
        - id: behavioral_segmentation
          type: Compose
          name: Behavioral Segmentation
          inputs:
            method: "behavioral"
            description: "Behavior-based clustering segmentation"
            segments:
              - segment_id: "beh_deal_seekers"
                segment_name: "Deal Seekers"
                size_percentage: 25
                characteristics:
                  description: "Price-sensitive shoppers who respond to promotions"
                  behaviors: ["coupon_user", "sale_shopper", "price_comparison"]
                  triggers: ["discounts", "flash_sales", "clearance"]
                recommended_priority: "secondary"
                media_preferences: ["email", "social_retargeting", "display"]
              - segment_id: "beh_brand_enthusiasts"
                segment_name: "Brand Enthusiasts"
                size_percentage: 15
                characteristics:
                  description: "Brand-loyal customers with emotional connection"
                  behaviors: ["social_follower", "review_writer", "brand_advocate"]
                  triggers: ["new_products", "brand_stories", "exclusivity"]
                recommended_priority: "primary"
                media_preferences: ["social_organic", "email", "video"]
              - segment_id: "beh_convenience"
                segment_name: "Convenience Shoppers"
                size_percentage: 30
                characteristics:
                  description: "Value speed and ease over price"
                  behaviors: ["mobile_shopper", "repeat_orderer", "subscription_user"]
                  triggers: ["speed", "simplicity", "auto_replenishment"]
                recommended_priority: "primary"
                media_preferences: ["mobile", "app_push", "sms"]
              - segment_id: "beh_researchers"
                segment_name: "Researchers"
                size_percentage: 30
                characteristics:
                  description: "Thorough decision-makers who need information"
                  behaviors: ["review_reader", "comparison_shopper", "long_consideration"]
                  triggers: ["detailed_specs", "reviews", "comparisons"]
                recommended_priority: "secondary"
                media_preferences: ["search", "video", "content_marketing"]

      demographic:
        - id: demographic_segmentation
          type: Compose
          name: Demographic Segmentation
          inputs:
            method: "demographic"
            description: "Demographics-based audience segmentation"
            segments:
              - segment_id: "demo_young_professionals"
                segment_name: "Young Professionals"
                age_range: [25, 34]
                size_percentage: 22
                characteristics:
                  income_level: "middle_to_upper"
                  life_stage: "career_building"
                  interests: ["technology", "experiences", "self_improvement"]
                recommended_priority: "primary"
                media_preferences: ["social", "streaming", "podcasts"]
              - segment_id: "demo_families"
                segment_name: "Family Households"
                age_range: [30, 45]
                size_percentage: 28
                characteristics:
                  income_level: "middle"
                  life_stage: "family_raising"
                  interests: ["value", "convenience", "family_activities"]
                recommended_priority: "primary"
                media_preferences: ["ctv", "social", "email"]
              - segment_id: "demo_affluent_mature"
                segment_name: "Affluent Mature"
                age_range: [45, 65]
                size_percentage: 18
                characteristics:
                  income_level: "upper"
                  life_stage: "established"
                  interests: ["quality", "travel", "wellness"]
                recommended_priority: "secondary"
                media_preferences: ["premium_video", "print", "email"]
              - segment_id: "demo_gen_z"
                segment_name: "Gen Z Emerging"
                age_range: [18, 24]
                size_percentage: 15
                characteristics:
                  income_level: "emerging"
                  life_stage: "exploring"
                  interests: ["social_causes", "authenticity", "digital_native"]
                recommended_priority: "secondary"
                media_preferences: ["tiktok", "instagram", "gaming"]

    default:
      - id: custom_segmentation
        type: Compose
        name: Custom Segmentation
        inputs:
          method: "custom"
          description: "Custom segmentation based on provided criteria"
          warning: "Custom segmentation requires additional configuration"
    run_after: parse_input

  # Step 3: Apply constraints
  - id: apply_constraints
    type: Compose
    name: Apply Constraints
    inputs:
      original_segments: "@coalesce(outputs('rfm_segmentation'), outputs('behavioral_segmentation'), outputs('demographic_segmentation'), outputs('custom_segmentation'))"
      applied_filters:
        minimum_size: "@outputs('parse_input')?['constraints']?['minimum_segment_size']"
        geographic: "@outputs('parse_input')?['constraints']?['geographic_focus']"
        excluded: "@outputs('parse_input')?['constraints']?['exclude_segments']"
    run_after: check_method

  # Step 4: Calculate segment sizes
  - id: calculate_sizes
    type: Compose
    name: Calculate Segment Sizes
    inputs:
      total_addressable_audience: 10000000
      segments_with_sizes: "@outputs('apply_constraints')?['original_segments']?['segments']"
      size_methodology: "percentage_based"
    run_after: apply_constraints

  # Step 5: Prioritize segments for campaign
  - id: prioritize_segments
    type: Compose
    name: Prioritize for Campaign
    inputs:
      campaign_objective: "@outputs('parse_input')?['campaign_context']?['objective']"
      budget: "@outputs('parse_input')?['campaign_context']?['budget']"
      prioritization:
        primary_segments: 2
        secondary_segments: 2
        recommendation: "Focus on primary segments for 70% of budget"
    run_after: calculate_sizes

  # Step 6: Build response
  - id: build_response
    type: Compose
    name: Build Response
    inputs:
      request_id: "@outputs('parse_input')?['request_id']"
      timestamp: "@utcNow()"
      source_agent: "AUD"
      status: "success"
      data:
        segmentation_method: "@outputs('parse_input')?['method']"
        data_source: "@outputs('parse_input')?['data_source']"
        segments: "@outputs('calculate_sizes')?['segments_with_sizes']"
        total_addressable_audience: "@outputs('calculate_sizes')?['total_addressable_audience']"
        prioritization: "@outputs('prioritize_segments')"
        methodology_description: "@outputs('apply_constraints')?['original_segments']?['description']"
      confidence: "HIGH"
      sources:
        - "AGENT_KB"
        - "CALCULATION"
      recommendations:
        - "Start with primary segments for initial campaign phase"
        - "Use secondary segments for expansion once primary is optimized"
        - "Monitor segment performance to refine targeting"
      updated_plan_state:
        audience:
          primary_segments: "@take(outputs('calculate_sizes')?['segments_with_sizes'], 2)"
          segmentation_method: "@outputs('parse_input')?['method']"
      metadata:
        processing_time_ms: "@div(sub(ticks(utcNow()), ticks(outputs('parse_input')?['start_time'])), 10000)"
    run_after: prioritize_segments

  # Step 7: Return response
  - id: return_response
    type: Response
    name: Return Response
    inputs:
      statusCode: 200
      headers:
        Content-Type: application/json
      body: "@outputs('build_response')"

error_handling:
  on_error:
    - id: return_error
      type: Response
      name: Return Error Response
      inputs:
        statusCode: 500
        headers:
          Content-Type: application/json
        body:
          request_id: "@outputs('parse_input')?['request_id']"
          source_agent: "AUD"
          error: true
          code: "SEGMENTATION_ERROR"
          message: "Failed to segment audience"
