# ApplyAnalysis Power Automate Flow Definition
# Version: 1.0.0
# Agent: CST (Consulting Strategy)
# Description: Executes strategic framework analysis and generates insights

name: ApplyAnalysis
description: >
  HTTP-triggered flow that executes a specified strategic framework analysis
  using provided inputs. Returns structured analysis, insights, and
  strategic recommendations.

trigger:
  type: HTTP
  method: POST
  schema:
    type: object
    required:
      - session_id
      - request_id
      - framework_code
      - inputs
    properties:
      session_id:
        type: string
        format: uuid
      request_id:
        type: string
        format: uuid
      framework_code:
        type: string
        enum: [SWOT, PESTEL, PORTER_FIVE_FORCES, BCG_MATRIX, ANSOFF_MATRIX, VALUE_CHAIN, MCKINSEY_7S]
      inputs:
        type: object
        description: Framework-specific input data
      context:
        type: object
        properties:
          company_name:
            type: string
          industry:
            type: string
          strategic_objective:
            type: string

environment_variables:
  EAP_DATAVERSE_URL:
    description: EAP Dataverse environment URL
    required: true

steps:
  # Step 1: Parse input
  - id: parse_input
    type: Compose
    name: Parse Input
    inputs:
      session_id: "@triggerBody()?['session_id']"
      request_id: "@triggerBody()?['request_id']"
      framework_code: "@triggerBody()?['framework_code']"
      inputs: "@triggerBody()?['inputs']"
      context: "@triggerBody()?['context']"
      start_time: "@utcNow()"

  # Step 2: Route by framework
  - id: route_framework
    type: Switch
    name: Route by Framework
    expression: "@outputs('parse_input')?['framework_code']"
    cases:
      SWOT:
        - id: apply_swot
          type: Compose
          name: Apply SWOT Analysis
          inputs:
            framework: "SWOT"
            analysis:
              strengths:
                items:
                  - factor: "Strong brand recognition"
                    impact: "high"
                    leverage_potential: "Market expansion, premium pricing"
                  - factor: "Proprietary technology"
                    impact: "high"
                    leverage_potential: "Competitive differentiation"
                  - factor: "Experienced leadership team"
                    impact: "medium"
                    leverage_potential: "Strategic decision quality"
                  - factor: "Strong customer relationships"
                    impact: "high"
                    leverage_potential: "Retention, upsell opportunities"
                summary: "Core strengths center on brand and technology assets"
              weaknesses:
                items:
                  - factor: "Limited geographic presence"
                    impact: "medium"
                    mitigation: "Strategic partnerships or expansion"
                  - factor: "Aging technology infrastructure"
                    impact: "high"
                    mitigation: "Modernization investment required"
                  - factor: "High customer acquisition cost"
                    impact: "medium"
                    mitigation: "Optimize marketing mix and channels"
                summary: "Key weaknesses require investment to address"
              opportunities:
                items:
                  - factor: "Growing market demand"
                    impact: "high"
                    capture_strategy: "Capacity expansion, new products"
                  - factor: "Competitor exit from segment"
                    impact: "high"
                    capture_strategy: "Aggressive market share capture"
                  - factor: "Technology partnership availability"
                    impact: "medium"
                    capture_strategy: "Evaluate strategic alliance"
                summary: "Significant opportunities exist in core market"
              threats:
                items:
                  - factor: "New market entrants"
                    impact: "medium"
                    mitigation: "Strengthen differentiation"
                  - factor: "Regulatory changes"
                    impact: "high"
                    mitigation: "Proactive compliance investment"
                  - factor: "Economic uncertainty"
                    impact: "medium"
                    mitigation: "Diversify revenue streams"
                summary: "Threats manageable with proactive strategy"
            strategic_implications:
              - implication: "Leverage brand and technology to capture growth opportunity"
                priority: "high"
                timeframe: "immediate"
              - implication: "Address infrastructure weakness before scaling"
                priority: "high"
                timeframe: "short_term"
              - implication: "Build competitive moat against new entrants"
                priority: "medium"
                timeframe: "medium_term"

      PORTER_FIVE_FORCES:
        - id: apply_porter
          type: Compose
          name: Apply Porter Five Forces
          inputs:
            framework: "PORTER_FIVE_FORCES"
            analysis:
              competitive_rivalry:
                intensity: "high"
                score: 4
                factors:
                  - "Multiple established competitors"
                  - "Slow industry growth"
                  - "Low differentiation"
                implications: "Requires strong differentiation strategy"
              threat_of_new_entrants:
                intensity: "medium"
                score: 3
                factors:
                  - "Moderate capital requirements"
                  - "Some regulatory barriers"
                  - "Established brand loyalty"
                implications: "Monitor emerging competitors"
              threat_of_substitutes:
                intensity: "medium"
                score: 3
                factors:
                  - "Alternative solutions exist"
                  - "Switching costs moderate"
                implications: "Invest in customer lock-in"
              bargaining_power_suppliers:
                intensity: "low"
                score: 2
                factors:
                  - "Multiple supplier options"
                  - "Standardized inputs"
                implications: "Favorable negotiating position"
              bargaining_power_buyers:
                intensity: "high"
                score: 4
                factors:
                  - "Price sensitivity"
                  - "Low switching costs"
                  - "Information availability"
                implications: "Focus on value demonstration"
            overall_industry_attractiveness:
              score: 55
              rating: "moderate"
              rationale: "Competitive but profitable with right positioning"
            strategic_implications:
              - implication: "Differentiation is critical success factor"
                priority: "high"
              - implication: "Customer retention more efficient than acquisition"
                priority: "high"
              - implication: "Leverage supplier power for margin improvement"
                priority: "medium"

      PESTEL:
        - id: apply_pestel
          type: Compose
          name: Apply PESTEL Analysis
          inputs:
            framework: "PESTEL"
            analysis:
              political:
                factors:
                  - factor: "Trade policy stability"
                    impact: "neutral"
                    trend: "stable"
                  - factor: "Government incentive programs"
                    impact: "positive"
                    trend: "favorable"
                overall_impact: "neutral_to_positive"
              economic:
                factors:
                  - factor: "GDP growth trajectory"
                    impact: "positive"
                    trend: "improving"
                  - factor: "Interest rate environment"
                    impact: "negative"
                    trend: "increasing"
                  - factor: "Consumer spending"
                    impact: "positive"
                    trend: "stable"
                overall_impact: "positive"
              social:
                factors:
                  - factor: "Demographic shifts"
                    impact: "positive"
                    trend: "favorable"
                  - factor: "Consumer preference changes"
                    impact: "positive"
                    trend: "favorable"
                overall_impact: "positive"
              technological:
                factors:
                  - factor: "Digital transformation acceleration"
                    impact: "positive"
                    trend: "accelerating"
                  - factor: "AI/automation adoption"
                    impact: "positive"
                    trend: "accelerating"
                overall_impact: "highly_positive"
              environmental:
                factors:
                  - factor: "Sustainability requirements"
                    impact: "neutral"
                    trend: "increasing"
                overall_impact: "neutral"
              legal:
                factors:
                  - factor: "Data privacy regulations"
                    impact: "negative"
                    trend: "increasing"
                  - factor: "Employment law changes"
                    impact: "neutral"
                    trend: "stable"
                overall_impact: "slightly_negative"
            strategic_implications:
              - implication: "Technology investments align with macro trends"
                priority: "high"
              - implication: "Economic conditions support growth initiatives"
                priority: "high"
              - implication: "Data privacy compliance requires attention"
                priority: "medium"
    default:
      - id: unsupported_framework
        type: Compose
        name: Unsupported Framework
        inputs:
          error: "Framework not yet supported"
          supported_frameworks:
            - "SWOT"
            - "PORTER_FIVE_FORCES"
            - "PESTEL"
    run_after: parse_input

  # Step 3: Generate synthesis
  - id: generate_synthesis
    type: Compose
    name: Generate Synthesis
    inputs:
      executive_summary: "Analysis reveals a moderately attractive strategic position with strong internal capabilities and favorable external trends. Key success factors include differentiation, technology investment, and customer retention focus."
      key_insights:
        - insight: "Internal strengths align well with external opportunities"
          confidence: "high"
          actionability: "immediate"
        - insight: "Infrastructure modernization is prerequisite for growth"
          confidence: "high"
          actionability: "short_term"
        - insight: "Competitive intensity requires sustained differentiation investment"
          confidence: "medium"
          actionability: "ongoing"
      strategic_options:
        - option: "Accelerated Growth"
          description: "Invest heavily in capturing market opportunity"
          risk_level: "medium"
          resource_requirement: "high"
          fit_score: 85
        - option: "Selective Investment"
          description: "Focused investment in highest-potential areas"
          risk_level: "low"
          resource_requirement: "medium"
          fit_score: 90
        - option: "Defensive Positioning"
          description: "Protect current position while building capabilities"
          risk_level: "low"
          resource_requirement: "low"
          fit_score: 70
      recommended_option: "Selective Investment"
      recommendation_rationale: "Best balance of growth capture and risk management given current capabilities"
    run_after: route_framework

  # Step 4: Build response
  - id: build_response
    type: Compose
    name: Build Response
    inputs:
      request_id: "@outputs('parse_input')?['request_id']"
      timestamp: "@utcNow()"
      source_agent: "CST"
      status: "success"
      data:
        framework_applied: "@outputs('parse_input')?['framework_code']"
        context: "@outputs('parse_input')?['context']"
        analysis: "@coalesce(outputs('apply_swot'), outputs('apply_porter'), outputs('apply_pestel'), outputs('unsupported_framework'))"
        synthesis:
          executive_summary: "@outputs('generate_synthesis')?['executive_summary']"
          key_insights: "@outputs('generate_synthesis')?['key_insights']"
          strategic_options: "@outputs('generate_synthesis')?['strategic_options']"
          recommended_option: "@outputs('generate_synthesis')?['recommended_option']"
          recommendation_rationale: "@outputs('generate_synthesis')?['recommendation_rationale']"
      confidence: "HIGH"
      sources:
        - "AGENT_KB"
        - "FRAMEWORK_ANALYSIS"
        - "INPUT_DATA"
      recommendations:
        - "Review analysis with leadership team"
        - "Validate assumptions with market data"
        - "Develop action plan for selected strategic option"
      follow_up_questions:
        - "Would you like to prioritize initiatives based on this analysis?"
        - "Should we apply additional frameworks for deeper insight?"
        - "Do you want to develop a detailed implementation roadmap?"
      metadata:
        processing_time_ms: "@div(sub(ticks(utcNow()), ticks(outputs('parse_input')?['start_time'])), 10000)"
    run_after: generate_synthesis

  # Step 5: Return response
  - id: return_response
    type: Response
    name: Return Response
    inputs:
      statusCode: 200
      headers:
        Content-Type: application/json
      body: "@outputs('build_response')"

error_handling:
  on_error:
    - id: return_error
      type: Response
      name: Return Error Response
      inputs:
        statusCode: 500
        headers:
          Content-Type: application/json
        body:
          request_id: "@outputs('parse_input')?['request_id']"
          source_agent: "CST"
          error: true
          code: "ANALYSIS_ERROR"
          message: "Failed to apply framework analysis"
