# PrioritizeInitiatives Power Automate Flow Definition
# Version: 1.0.0
# Agent: CST (Consulting Strategy)
# Description: Scores and ranks strategic initiatives using prioritization methods

name: PrioritizeInitiatives
description: >
  HTTP-triggered flow that prioritizes strategic initiatives using various
  scoring methodologies including weighted criteria, ICE, RICE, and value-effort
  matrices. Returns ranked initiatives with scores and recommendations.

trigger:
  type: HTTP
  method: POST
  schema:
    type: object
    required:
      - session_id
      - request_id
      - items
    properties:
      session_id:
        type: string
        format: uuid
      request_id:
        type: string
        format: uuid
      method:
        type: string
        enum: [weighted_criteria, ice, rice, value_effort]
        default: weighted_criteria
      items:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            description:
              type: string
            estimated_value:
              type: number
            estimated_effort:
              type: number
      criteria:
        type: array
        items:
          type: object
          properties:
            criterion:
              type: string
            weight:
              type: number
      constraints:
        type: object
        properties:
          max_initiatives:
            type: integer
          budget_limit:
            type: number
          resource_limit:
            type: number

environment_variables:
  EAP_DATAVERSE_URL:
    description: EAP Dataverse environment URL
    required: true

steps:
  # Step 1: Parse input
  - id: parse_input
    type: Compose
    name: Parse Input
    inputs:
      session_id: "@triggerBody()?['session_id']"
      request_id: "@triggerBody()?['request_id']"
      method: "@coalesce(triggerBody()?['method'], 'weighted_criteria')"
      items: "@triggerBody()?['items']"
      criteria: "@triggerBody()?['criteria']"
      constraints: "@triggerBody()?['constraints']"
      start_time: "@utcNow()"

  # Step 2: Route by prioritization method
  - id: route_method
    type: Switch
    name: Route by Method
    expression: "@outputs('parse_input')?['method']"
    cases:
      weighted_criteria:
        - id: apply_weighted_criteria
          type: Compose
          name: Apply Weighted Criteria
          inputs:
            method: "Weighted Criteria Scoring"
            description: "Multi-criteria scoring with customizable weights"
            criteria_used:
              - criterion: "Strategic Alignment"
                weight: 25
                description: "Fit with strategic objectives"
              - criterion: "Financial Impact"
                weight: 30
                description: "Revenue/cost impact potential"
              - criterion: "Feasibility"
                weight: 20
                description: "Technical and operational feasibility"
              - criterion: "Time to Value"
                weight: 15
                description: "Speed of value realization"
              - criterion: "Risk Level"
                weight: 10
                description: "Implementation and market risk"
            scored_items:
              - id: "INI001"
                name: "Digital Platform Modernization"
                scores:
                  strategic_alignment: 9
                  financial_impact: 8
                  feasibility: 7
                  time_to_value: 5
                  risk_level: 6
                weighted_score: 7.55
                rank: 1
              - id: "INI002"
                name: "Customer Experience Enhancement"
                scores:
                  strategic_alignment: 8
                  financial_impact: 9
                  feasibility: 8
                  time_to_value: 7
                  risk_level: 8
                weighted_score: 8.15
                rank: 2
              - id: "INI003"
                name: "Market Expansion - Region A"
                scores:
                  strategic_alignment: 9
                  financial_impact: 9
                  feasibility: 6
                  time_to_value: 4
                  risk_level: 5
                weighted_score: 7.35
                rank: 3
              - id: "INI004"
                name: "Operational Efficiency Program"
                scores:
                  strategic_alignment: 7
                  financial_impact: 7
                  feasibility: 9
                  time_to_value: 8
                  risk_level: 9
                weighted_score: 7.65
                rank: 4
              - id: "INI005"
                name: "New Product Development"
                scores:
                  strategic_alignment: 8
                  financial_impact: 8
                  feasibility: 5
                  time_to_value: 3
                  risk_level: 4
                weighted_score: 6.35
                rank: 5

      ice:
        - id: apply_ice
          type: Compose
          name: Apply ICE Scoring
          inputs:
            method: "ICE Scoring"
            description: "Impact, Confidence, Ease scoring method"
            scoring_scale: "1-10 for each dimension"
            scored_items:
              - id: "INI001"
                name: "Digital Platform Modernization"
                impact: 9
                confidence: 7
                ease: 5
                ice_score: 315
                rank: 2
              - id: "INI002"
                name: "Customer Experience Enhancement"
                impact: 8
                confidence: 8
                ease: 7
                ice_score: 448
                rank: 1
              - id: "INI003"
                name: "Market Expansion - Region A"
                impact: 9
                confidence: 6
                ease: 4
                ice_score: 216
                rank: 4
              - id: "INI004"
                name: "Operational Efficiency Program"
                impact: 7
                confidence: 9
                ease: 8
                ice_score: 504
                rank: 3
              - id: "INI005"
                name: "New Product Development"
                impact: 8
                confidence: 5
                ease: 4
                ice_score: 160
                rank: 5

      rice:
        - id: apply_rice
          type: Compose
          name: Apply RICE Scoring
          inputs:
            method: "RICE Scoring"
            description: "Reach, Impact, Confidence, Effort scoring method"
            scored_items:
              - id: "INI001"
                name: "Digital Platform Modernization"
                reach: 5000
                impact: 3
                confidence: 70
                effort: 8
                rice_score: 1312
                rank: 2
              - id: "INI002"
                name: "Customer Experience Enhancement"
                reach: 10000
                impact: 2
                confidence: 80
                effort: 5
                rice_score: 3200
                rank: 1
              - id: "INI003"
                name: "Market Expansion - Region A"
                reach: 3000
                impact: 3
                confidence: 60
                effort: 10
                rice_score: 540
                rank: 4
              - id: "INI004"
                name: "Operational Efficiency Program"
                reach: 2000
                impact: 2
                confidence: 90
                effort: 4
                rice_score: 900
                rank: 3
              - id: "INI005"
                name: "New Product Development"
                reach: 2000
                impact: 3
                confidence: 50
                effort: 12
                rice_score: 250
                rank: 5

      value_effort:
        - id: apply_value_effort
          type: Compose
          name: Apply Value-Effort Matrix
          inputs:
            method: "Value-Effort Matrix"
            description: "2x2 prioritization based on value and effort"
            quadrants:
              quick_wins:
                description: "High value, low effort - Do first"
                items:
                  - "Customer Experience Enhancement"
                  - "Operational Efficiency Program"
              major_projects:
                description: "High value, high effort - Plan carefully"
                items:
                  - "Digital Platform Modernization"
                  - "Market Expansion - Region A"
              fill_ins:
                description: "Low value, low effort - Do if capacity allows"
                items: []
              thankless_tasks:
                description: "Low value, high effort - Avoid or reconsider"
                items:
                  - "New Product Development"
            scored_items:
              - id: "INI002"
                name: "Customer Experience Enhancement"
                value_score: 8.5
                effort_score: 4
                quadrant: "quick_wins"
                rank: 1
              - id: "INI004"
                name: "Operational Efficiency Program"
                value_score: 7.5
                effort_score: 3.5
                quadrant: "quick_wins"
                rank: 2
              - id: "INI001"
                name: "Digital Platform Modernization"
                value_score: 8
                effort_score: 7
                quadrant: "major_projects"
                rank: 3
              - id: "INI003"
                name: "Market Expansion - Region A"
                value_score: 8
                effort_score: 8
                quadrant: "major_projects"
                rank: 4
              - id: "INI005"
                name: "New Product Development"
                value_score: 6
                effort_score: 9
                quadrant: "thankless_tasks"
                rank: 5
    default:
      - id: default_method
        type: Compose
        name: Default Method
        inputs:
          message: "Defaulting to weighted criteria method"
    run_after: parse_input

  # Step 3: Apply constraints
  - id: apply_constraints
    type: Compose
    name: Apply Constraints
    inputs:
      constraints_applied:
        max_initiatives: "@coalesce(outputs('parse_input')?['constraints']?['max_initiatives'], 5)"
        budget_limit: "@outputs('parse_input')?['constraints']?['budget_limit']"
        resource_limit: "@outputs('parse_input')?['constraints']?['resource_limit']"
      filtered_recommendations:
        tier_1_recommended:
          - id: "INI002"
            name: "Customer Experience Enhancement"
            recommendation: "Execute immediately"
            rationale: "Highest risk-adjusted return"
          - id: "INI001"
            name: "Digital Platform Modernization"
            recommendation: "Execute in parallel"
            rationale: "Critical enabler for other initiatives"
        tier_2_recommended:
          - id: "INI004"
            name: "Operational Efficiency Program"
            recommendation: "Start after Tier 1 progress"
            rationale: "Good value, low complexity"
        tier_3_defer:
          - id: "INI003"
            name: "Market Expansion - Region A"
            recommendation: "Defer pending market validation"
            rationale: "High effort, uncertain return"
          - id: "INI005"
            name: "New Product Development"
            recommendation: "Reconsider scope or approach"
            rationale: "Current plan has unfavorable effort-value ratio"
    run_after: route_method

  # Step 4: Generate roadmap suggestion
  - id: generate_roadmap
    type: Compose
    name: Generate Roadmap Suggestion
    inputs:
      suggested_roadmap:
        q1:
          focus: "Foundation and Quick Wins"
          initiatives:
            - name: "Customer Experience Enhancement"
              allocation: 40
            - name: "Digital Platform Modernization - Phase 1"
              allocation: 60
        q2:
          focus: "Continued Development"
          initiatives:
            - name: "Digital Platform Modernization - Phase 2"
              allocation: 50
            - name: "Operational Efficiency Program"
              allocation: 50
        q3:
          focus: "Expansion Preparation"
          initiatives:
            - name: "Digital Platform Modernization - Phase 3"
              allocation: 30
            - name: "Operational Efficiency Program"
              allocation: 40
            - name: "Market Expansion - Planning"
              allocation: 30
        q4:
          focus: "Scale and Launch"
          initiatives:
            - name: "Market Expansion - Region A - Execution"
              allocation: 60
            - name: "Optimization and Refinement"
              allocation: 40
      resource_requirements:
        total_fte: 25
        peak_fte: 30
        estimated_investment: 5000000
    run_after: apply_constraints

  # Step 5: Build response
  - id: build_response
    type: Compose
    name: Build Response
    inputs:
      request_id: "@outputs('parse_input')?['request_id']"
      timestamp: "@utcNow()"
      source_agent: "CST"
      status: "success"
      data:
        method_used: "@outputs('parse_input')?['method']"
        items_evaluated: "@length(outputs('parse_input')?['items'])"
        scoring_results: "@coalesce(outputs('apply_weighted_criteria'), outputs('apply_ice'), outputs('apply_rice'), outputs('apply_value_effort'), outputs('default_method'))"
        prioritized_tiers: "@outputs('apply_constraints')?['filtered_recommendations']"
        suggested_roadmap: "@outputs('generate_roadmap')?['suggested_roadmap']"
        resource_summary: "@outputs('generate_roadmap')?['resource_requirements']"
      confidence: "HIGH"
      sources:
        - "AGENT_KB"
        - "CALCULATION"
        - "INPUT_DATA"
      recommendations:
        - "Focus resources on Tier 1 initiatives for maximum impact"
        - "Use quick wins to build momentum and stakeholder confidence"
        - "Revisit Tier 3 items after completing initial phases"
      follow_up_questions:
        - "Would you like to apply a different prioritization method?"
        - "Should we develop detailed project plans for top initiatives?"
        - "Do you want to conduct a strategic framework analysis?"
      metadata:
        processing_time_ms: "@div(sub(ticks(utcNow()), ticks(outputs('parse_input')?['start_time'])), 10000)"
    run_after: generate_roadmap

  # Step 6: Return response
  - id: return_response
    type: Response
    name: Return Response
    inputs:
      statusCode: 200
      headers:
        Content-Type: application/json
      body: "@outputs('build_response')"

error_handling:
  on_error:
    - id: return_error
      type: Response
      name: Return Error Response
      inputs:
        statusCode: 500
        headers:
          Content-Type: application/json
        body:
          request_id: "@outputs('parse_input')?['request_id']"
          source_agent: "CST"
          error: true
          code: "PRIORITIZATION_ERROR"
          message: "Failed to prioritize initiatives"
