# GetGrowthState Power Automate Flow Definition
# Version: 1.0.0
# Agent: GHA (Growth Hacking Agent)
# Description: Retrieves current growth session state and growth plan data from EAP

name: GetGrowthState
description: >
  HTTP-triggered flow that retrieves the current growth session state from EAP Dataverse.
  Returns the full growth context including workflow step, gate, and growth plan state.
  Used by GHA Copilot to provide context-aware growth strategy responses.
  Operates on eap_growth_sessions table, separate from main eap_sessions.

trigger:
  type: HTTP
  method: GET
  schema:
    type: object
    required:
      - session_id
    properties:
      session_id:
        type: string
        format: uuid
        description: Main session identifier to retrieve growth state for
      growth_session_id:
        type: string
        format: uuid
        description: Direct growth session identifier if known
      include_history:
        type: boolean
        default: false
        description: Include growth workflow history summary
      include_specialist_calls:
        type: boolean
        default: false
        description: Include recent specialist call logs

environment_variables:
  EAP_DATAVERSE_URL:
    description: EAP Dataverse environment URL
    required: true

steps:
  # Step 1: Parse input parameters
  - id: parse_input
    type: Compose
    name: Parse Input
    inputs:
      session_id: "@triggerBody()?['session_id']"
      growth_session_id: "@triggerBody()?['growth_session_id']"
      include_history: "@coalesce(triggerBody()?['include_history'], false)"
      include_specialist_calls: "@coalesce(triggerBody()?['include_specialist_calls'], false)"
      request_timestamp: "@utcNow()"

  # Step 2: Get growth session from Dataverse
  - id: get_growth_session
    type: HTTP
    name: Get Growth Session from Dataverse
    inputs:
      method: GET
      uri: "@if(empty(outputs('parse_input')?['growth_session_id']), concat(variables('EAP_DATAVERSE_URL'), '/api/data/v9.2/eap_growth_sessions?$filter=eap_session_id eq ''', outputs('parse_input')?['session_id'], ''''), concat(variables('EAP_DATAVERSE_URL'), '/api/data/v9.2/eap_growth_sessions(', outputs('parse_input')?['growth_session_id'], ')'))"
      headers:
        Authorization: "Bearer @{body('Get_Access_Token')?['access_token']}"
        Content-Type: application/json
        Prefer: "odata.include-annotations=*"
    run_after: parse_input

  # Step 3: Check if growth session exists
  - id: check_session_exists
    type: Condition
    name: Growth Session Exists?
    expression:
      or:
        - and:
            - not:
                equals:
                  - "@outputs('get_growth_session')?['statusCode']"
                  - 404
            - not:
                empty:
                  - "@body('get_growth_session')?['value']"
        - not:
            equals:
              - "@outputs('get_growth_session')?['statusCode']"
              - 404
    run_after: get_growth_session

  # Step 4a: Session exists - Parse growth session data
  - id: parse_growth_session
    type: Compose
    name: Parse Growth Session Data
    condition: check_session_exists.true
    inputs:
      growth_session_id: "@coalesce(body('get_growth_session')?['eap_growth_sessionid'], first(body('get_growth_session')?['value'])?['eap_growth_sessionid'])"
      session_id: "@coalesce(body('get_growth_session')?['eap_session_id'], first(body('get_growth_session')?['value'])?['eap_session_id'])"
      growth_workflow_step: "@coalesce(body('get_growth_session')?['eap_growth_workflow_step'], first(body('get_growth_session')?['value'])?['eap_growth_workflow_step'], 1)"
      growth_workflow_gate: "@coalesce(body('get_growth_session')?['eap_growth_workflow_gate'], first(body('get_growth_session')?['value'])?['eap_growth_workflow_gate'], 0)"
      growth_plan_state: "@json(coalesce(body('get_growth_session')?['eap_growth_plan_state'], first(body('get_growth_session')?['value'])?['eap_growth_plan_state'], '{}'))"
      north_star_metric: "@coalesce(body('get_growth_session')?['eap_north_star_metric'], first(body('get_growth_session')?['value'])?['eap_north_star_metric'])"
      priority_stages: "@json(coalesce(body('get_growth_session')?['eap_priority_stages'], first(body('get_growth_session')?['value'])?['eap_priority_stages'], '[]'))"
      created_at: "@coalesce(body('get_growth_session')?['createdon'], first(body('get_growth_session')?['value'])?['createdon'])"
      updated_at: "@coalesce(body('get_growth_session')?['modifiedon'], first(body('get_growth_session')?['value'])?['modifiedon'])"
    run_after: check_session_exists

  # Step 5: Get growth workflow gate details
  - id: get_gate_details
    type: Compose
    name: Get Growth Workflow Gate Details
    condition: check_session_exists.true
    inputs:
      gate_number: "@outputs('parse_growth_session')?['growth_workflow_gate']"
      gate_name: "@if(equals(outputs('parse_growth_session')?['growth_workflow_gate'], 0), 'Pre-Foundation', if(equals(outputs('parse_growth_session')?['growth_workflow_gate'], 1), 'Growth Foundation', if(equals(outputs('parse_growth_session')?['growth_workflow_gate'], 2), 'Growth Strategy', if(equals(outputs('parse_growth_session')?['growth_workflow_gate'], 3), 'Growth Tactics', 'Growth Plan Complete'))))"
      gate_steps:
        - gate: 0
          steps: []
          name: "Pre-Foundation"
        - gate: 1
          steps: [1, 2]
          name: "Growth Foundation"
          requirements:
            - "Business model documented"
            - "Growth stage identified"
            - "North Star metric selected with targets"
        - gate: 2
          steps: [3, 4]
          name: "Growth Strategy"
          requirements:
            - "Lifecycle analysis complete"
            - "Priority stages identified"
            - "Audience strategy defined"
        - gate: 3
          steps: [5, 6, 7]
          name: "Growth Tactics"
          requirements:
            - "Tactics selected with rationale"
            - "Channels recommended"
            - "Projections calculated"
        - gate: 4
          steps: [8]
          name: "Growth Plan Complete"
          requirements:
            - "Documentation generated"
            - "Handoff context prepared"
            - "Success metrics defined"
    run_after: parse_growth_session

  # Step 6: Calculate completion status
  - id: calculate_completion
    type: Compose
    name: Calculate Completion Status
    condition: check_session_exists.true
    inputs:
      current_step: "@outputs('parse_growth_session')?['growth_workflow_step']"
      total_steps: 8
      completion_percentage: "@mul(div(outputs('parse_growth_session')?['growth_workflow_step'], 8), 100)"
      steps_completed: "@sub(outputs('parse_growth_session')?['growth_workflow_step'], 1)"
      steps_remaining: "@sub(8, outputs('parse_growth_session')?['growth_workflow_step'])"
      growth_plan_state_fields_populated: "@length(intersection(createArray('business_model', 'growth_stage', 'north_star_metric', 'lifecycle_analysis', 'priority_stages', 'audience_segments', 'tactics', 'channel_strategy', 'projections', 'growth_plan_document'), json(coalesce(body('get_growth_session')?['eap_growth_plan_state'], first(body('get_growth_session')?['value'])?['eap_growth_plan_state'], '{}'))))"
    run_after: get_gate_details

  # Step 7: Condition - Include specialist call logs
  - id: check_include_specialist_calls
    type: Condition
    name: Include Specialist Calls?
    condition: check_session_exists.true
    expression:
      equals:
        - "@outputs('parse_input')?['include_specialist_calls']"
        - true
    run_after: calculate_completion

  # Step 8a: Get recent specialist routing logs for this growth session
  - id: get_specialist_logs
    type: HTTP
    name: Get Recent Specialist Call Logs
    condition: check_include_specialist_calls.true
    inputs:
      method: GET
      uri: "@{variables('EAP_DATAVERSE_URL')}/api/data/v9.2/eap_routing_logs?$filter=eap_source_agent eq 'GHA' and eap_session_id eq '@{outputs('parse_input')?['session_id']}'&$orderby=createdon desc&$top=20"
      headers:
        Authorization: "Bearer @{body('Get_Access_Token')?['access_token']}"
        Content-Type: application/json
    run_after: check_include_specialist_calls

  # Step 9: Build specialist call summary
  - id: build_specialist_summary
    type: Compose
    name: Build Specialist Call Summary
    condition: check_include_specialist_calls.true
    inputs:
      recent_specialist_calls: "@body('get_specialist_logs')?['value']"
      call_count: "@length(body('get_specialist_logs')?['value'])"
      specialists_called: "@union(body('get_specialist_logs')?['value'], 'eap_target_agent')"
    run_after: get_specialist_logs

  # Step 10: Build full response
  - id: build_response
    type: Compose
    name: Build Full Response
    condition: check_session_exists.true
    inputs:
      growth_session_context: "@outputs('parse_growth_session')"
      workflow_details:
        current_gate: "@outputs('get_gate_details')"
        completion: "@outputs('calculate_completion')"
        step_names:
          - step: 1
            name: "Growth Context"
            gate: 1
          - step: 2
            name: "North Star Definition"
            gate: 1
          - step: 3
            name: "Lifecycle Analysis"
            gate: 2
          - step: 4
            name: "Audience Strategy"
            gate: 2
          - step: 5
            name: "Tactics Development"
            gate: 3
          - step: 6
            name: "Channel Strategy"
            gate: 3
          - step: 7
            name: "Projections"
            gate: 3
          - step: 8
            name: "Growth Plan Documentation"
            gate: 4
      specialist_summary: "@if(outputs('parse_input')?['include_specialist_calls'], outputs('build_specialist_summary'), null)"
      metadata:
        retrieved_at: "@utcNow()"
        request_session_id: "@outputs('parse_input')?['session_id']"
    run_after:
      - calculate_completion
      - build_specialist_summary

  # Step 4b: Session not found - Build error response
  - id: build_not_found_response
    type: Compose
    name: Build Not Found Response
    condition: check_session_exists.false
    inputs:
      error: true
      code: "GROWTH_SESSION_NOT_FOUND"
      message: "Growth session not found"
      session_id: "@outputs('parse_input')?['session_id']"
      suggestion: "Create a new growth session or verify the session ID"
      can_create: true
    run_after: check_session_exists

  # Step 11: Return response
  - id: return_response
    type: Response
    name: Return Response
    inputs:
      statusCode: "@if(outputs('check_session_exists'), 200, 404)"
      headers:
        Content-Type: application/json
      body: "@coalesce(outputs('build_response'), outputs('build_not_found_response'))"

error_handling:
  on_error:
    - id: return_error
      type: Response
      name: Return Error Response
      inputs:
        statusCode: 500
        headers:
          Content-Type: application/json
        body:
          error: true
          code: "INTERNAL_ERROR"
          message: "Failed to retrieve growth session state"
          session_id: "@outputs('parse_input')?['session_id']"
