# AnalyzePerformance Power Automate Flow Definition
# Version: 1.0.0
# Agent: PRF (Performance Intelligence)
# Description: Analyzes campaign performance metrics against targets with severity assessment

name: AnalyzePerformance
description: >
  HTTP-triggered flow that analyzes campaign performance metrics against targets,
  calculates variance, determines severity level, and provides actionable
  recommendations based on performance status.

trigger:
  type: HTTP
  method: POST
  schema:
    type: object
    required:
      - session_id
      - request_id
      - metric
      - actual
      - target
    properties:
      session_id:
        type: string
        format: uuid
      request_id:
        type: string
        format: uuid
      metric:
        type: string
        enum: [CPA, CPM, CTR, CVR, ROAS, FREQUENCY, VIEWABILITY, VCR]
      actual:
        type: number
        description: Actual metric value
      target:
        type: number
        description: Target metric value
      prior_period:
        type: number
        description: Prior period value for trend analysis
      campaign_id:
        type: string
      campaign_phase:
        type: string
        enum: [LAUNCH, LEARNING, OPTIMIZATION, MATURE]
        default: OPTIMIZATION

environment_variables:
  EAP_DATAVERSE_URL:
    description: EAP Dataverse environment URL
    required: true

steps:
  # Step 1: Parse input
  - id: parse_input
    type: Compose
    name: Parse Input
    inputs:
      session_id: "@triggerBody()?['session_id']"
      request_id: "@triggerBody()?['request_id']"
      metric: "@triggerBody()?['metric']"
      actual: "@triggerBody()?['actual']"
      target: "@triggerBody()?['target']"
      prior_period: "@triggerBody()?['prior_period']"
      campaign_id: "@coalesce(triggerBody()?['campaign_id'], 'UNKNOWN')"
      campaign_phase: "@coalesce(triggerBody()?['campaign_phase'], 'OPTIMIZATION')"
      start_time: "@utcNow()"

  # Step 2: Load metric thresholds
  - id: load_thresholds
    type: Compose
    name: Load Metric Thresholds
    inputs:
      thresholds:
        CPA:
          yellow: 10
          orange: 20
          red: 35
          direction: "lower_is_better"
          description: "Cost Per Acquisition"
        CPM:
          yellow: 15
          orange: 25
          red: 40
          direction: "lower_is_better"
          description: "Cost Per Mille"
        CTR:
          yellow: 20
          orange: 35
          red: 50
          direction: "higher_is_better"
          description: "Click-Through Rate"
        CVR:
          yellow: 15
          orange: 25
          red: 40
          direction: "higher_is_better"
          description: "Conversion Rate"
        ROAS:
          yellow: 15
          orange: 30
          red: 50
          direction: "higher_is_better"
          description: "Return On Ad Spend"
        FREQUENCY:
          yellow: 20
          orange: 40
          red: 60
          direction: "target_range"
          description: "Average Frequency"
        VIEWABILITY:
          yellow: 10
          orange: 20
          red: 30
          direction: "higher_is_better"
          description: "Viewability Rate"
        VCR:
          yellow: 15
          orange: 25
          red: 40
          direction: "higher_is_better"
          description: "Video Completion Rate"
    run_after: parse_input

  # Step 3: Calculate variance
  - id: calculate_variance
    type: Compose
    name: Calculate Variance
    inputs:
      actual: "@outputs('parse_input')?['actual']"
      target: "@outputs('parse_input')?['target']"
      absolute_variance: "@sub(outputs('parse_input')?['actual'], outputs('parse_input')?['target'])"
      variance_percent: "@if(equals(outputs('parse_input')?['target'], 0), 0, mul(div(sub(outputs('parse_input')?['actual'], outputs('parse_input')?['target']), outputs('parse_input')?['target']), 100))"
      direction: "@outputs('load_thresholds')?['thresholds']?[outputs('parse_input')?['metric']]?['direction']"
    run_after: load_thresholds

  # Step 4: Determine performance direction
  - id: determine_direction
    type: Compose
    name: Determine Performance Direction
    inputs:
      variance_percent: "@outputs('calculate_variance')?['variance_percent']"
      direction: "@outputs('calculate_variance')?['direction']"
      is_favorable: "@if(equals(outputs('calculate_variance')?['direction'], 'lower_is_better'), less(outputs('parse_input')?['actual'], outputs('parse_input')?['target']), if(equals(outputs('calculate_variance')?['direction'], 'higher_is_better'), greater(outputs('parse_input')?['actual'], outputs('parse_input')?['target']), and(greater(outputs('parse_input')?['actual'], mul(outputs('parse_input')?['target'], 0.8)), less(outputs('parse_input')?['actual'], mul(outputs('parse_input')?['target'], 1.2)))))"
      adjusted_variance: "@if(equals(outputs('calculate_variance')?['direction'], 'lower_is_better'), mul(outputs('calculate_variance')?['variance_percent'], -1), outputs('calculate_variance')?['variance_percent'])"
    run_after: calculate_variance

  # Step 5: Determine severity
  - id: determine_severity
    type: Compose
    name: Determine Severity Level
    inputs:
      metric: "@outputs('parse_input')?['metric']"
      variance_abs: "@abs(outputs('calculate_variance')?['variance_percent'])"
      thresholds: "@outputs('load_thresholds')?['thresholds']?[outputs('parse_input')?['metric']]"
      severity: "@if(greater(abs(outputs('calculate_variance')?['variance_percent']), outputs('load_thresholds')?['thresholds']?[outputs('parse_input')?['metric']]?['red']), 'RED', if(greater(abs(outputs('calculate_variance')?['variance_percent']), outputs('load_thresholds')?['thresholds']?[outputs('parse_input')?['metric']]?['orange']), 'ORANGE', if(greater(abs(outputs('calculate_variance')?['variance_percent']), outputs('load_thresholds')?['thresholds']?[outputs('parse_input')?['metric']]?['yellow']), 'YELLOW', 'GREEN')))"
      is_favorable: "@outputs('determine_direction')?['is_favorable']"
    run_after: determine_direction

  # Step 6: Calculate trend
  - id: calculate_trend
    type: Compose
    name: Calculate Trend
    inputs:
      has_prior_period: "@not(equals(outputs('parse_input')?['prior_period'], null))"
      prior_period: "@outputs('parse_input')?['prior_period']"
      actual: "@outputs('parse_input')?['actual']"
      period_change_percent: "@if(equals(outputs('parse_input')?['prior_period'], null), null, if(equals(outputs('parse_input')?['prior_period'], 0), null, mul(div(sub(outputs('parse_input')?['actual'], outputs('parse_input')?['prior_period']), outputs('parse_input')?['prior_period']), 100)))"
      trend: "@if(equals(outputs('parse_input')?['prior_period'], null), 'UNKNOWN', if(greater(mul(div(sub(outputs('parse_input')?['actual'], outputs('parse_input')?['prior_period']), if(equals(outputs('parse_input')?['prior_period'], 0), 1, outputs('parse_input')?['prior_period'])), 100), 10), 'IMPROVING', if(less(mul(div(sub(outputs('parse_input')?['actual'], outputs('parse_input')?['prior_period']), if(equals(outputs('parse_input')?['prior_period'], 0), 1, outputs('parse_input')?['prior_period'])), 100), -10), 'DECLINING', 'STABLE')))"
    run_after: determine_severity

  # Step 7: Determine action
  - id: determine_action
    type: Compose
    name: Determine Required Action
    inputs:
      severity: "@outputs('determine_severity')?['severity']"
      is_favorable: "@outputs('determine_severity')?['is_favorable']"
      action: "@if(and(equals(outputs('determine_severity')?['severity'], 'RED'), not(outputs('determine_severity')?['is_favorable'])), 'IMMEDIATE_ACTION', if(and(equals(outputs('determine_severity')?['severity'], 'ORANGE'), not(outputs('determine_severity')?['is_favorable'])), 'ACTION_WITHIN_24H', if(and(equals(outputs('determine_severity')?['severity'], 'YELLOW'), not(outputs('determine_severity')?['is_favorable'])), 'REVIEW_WITHIN_48H', 'CONTINUE_MONITORING')))"
      action_descriptions:
        IMMEDIATE_ACTION: "Critical variance detected. Requires immediate intervention."
        ACTION_WITHIN_24H: "Significant variance. Review and adjust within 24 hours."
        REVIEW_WITHIN_48H: "Moderate variance. Schedule review within 48 hours."
        CONTINUE_MONITORING: "Performance within acceptable range. Continue monitoring."
    run_after: calculate_trend

  # Step 8: Generate recommendations
  - id: generate_recommendations
    type: Compose
    name: Generate Recommendations
    inputs:
      metric: "@outputs('parse_input')?['metric']"
      severity: "@outputs('determine_severity')?['severity']"
      is_favorable: "@outputs('determine_severity')?['is_favorable']"
      recommendations:
        unfavorable:
          CPA:
            - "Review targeting parameters for efficiency"
            - "Analyze conversion funnel for drop-off points"
            - "Consider reducing bids on underperforming segments"
          CPM:
            - "Evaluate inventory sources for cost efficiency"
            - "Consider moving budget to lower-cost placements"
            - "Review frequency caps to reduce waste"
          CTR:
            - "Test new creative variations"
            - "Review audience targeting relevance"
            - "Evaluate placement quality"
          CVR:
            - "Analyze landing page performance"
            - "Review audience quality signals"
            - "Test conversion path optimization"
          ROAS:
            - "Shift budget to higher-performing channels"
            - "Review attribution window settings"
            - "Analyze product/offer mix"
        favorable:
          general:
            - "Document successful tactics for replication"
            - "Consider scaling budget to capture opportunity"
            - "Monitor for sustainability"
    run_after: determine_action

  # Step 9: Build response
  - id: build_response
    type: Compose
    name: Build Response
    inputs:
      request_id: "@outputs('parse_input')?['request_id']"
      timestamp: "@utcNow()"
      source_agent: "PRF"
      status: "success"
      data:
        performance_analysis:
          metric: "@outputs('parse_input')?['metric']"
          metric_description: "@outputs('load_thresholds')?['thresholds']?[outputs('parse_input')?['metric']]?['description']"
          actual: "@outputs('parse_input')?['actual']"
          target: "@outputs('parse_input')?['target']"
          variance_percent: "@outputs('calculate_variance')?['variance_percent']"
          absolute_variance: "@outputs('calculate_variance')?['absolute_variance']"
        assessment:
          severity: "@outputs('determine_severity')?['severity']"
          is_favorable: "@outputs('determine_severity')?['is_favorable']"
          action: "@outputs('determine_action')?['action']"
          action_description: "@outputs('determine_action')?['action_descriptions']?[outputs('determine_action')?['action']]"
        trend_analysis:
          trend: "@outputs('calculate_trend')?['trend']"
          period_change_percent: "@outputs('calculate_trend')?['period_change_percent']"
          prior_period_value: "@outputs('parse_input')?['prior_period']"
        thresholds_applied:
          yellow_threshold: "@outputs('load_thresholds')?['thresholds']?[outputs('parse_input')?['metric']]?['yellow']"
          orange_threshold: "@outputs('load_thresholds')?['thresholds']?[outputs('parse_input')?['metric']]?['orange']"
          red_threshold: "@outputs('load_thresholds')?['thresholds']?[outputs('parse_input')?['metric']]?['red']"
        context:
          campaign_id: "@outputs('parse_input')?['campaign_id']"
          campaign_phase: "@outputs('parse_input')?['campaign_phase']"
        recommendations: "@if(outputs('determine_severity')?['is_favorable'], outputs('generate_recommendations')?['recommendations']?['favorable']?['general'], coalesce(outputs('generate_recommendations')?['recommendations']?['unfavorable']?[outputs('parse_input')?['metric']], outputs('generate_recommendations')?['recommendations']?['favorable']?['general']))"
      confidence: "@if(equals(outputs('determine_severity')?['severity'], 'GREEN'), 'HIGH', if(equals(outputs('determine_severity')?['severity'], 'YELLOW'), 'HIGH', 'MEDIUM'))"
      sources:
        - "CALCULATION"
        - "AGENT_KB"
      metadata:
        processing_time_ms: "@div(sub(ticks(utcNow()), ticks(outputs('parse_input')?['start_time'])), 10000)"
    run_after: generate_recommendations

  # Step 10: Return response
  - id: return_response
    type: Response
    name: Return Response
    inputs:
      statusCode: 200
      headers:
        Content-Type: application/json
      body: "@outputs('build_response')"

error_handling:
  on_error:
    - id: return_error
      type: Response
      name: Return Error Response
      inputs:
        statusCode: 500
        headers:
          Content-Type: application/json
        body:
          request_id: "@outputs('parse_input')?['request_id']"
          source_agent: "PRF"
          error: true
          code: "PERFORMANCE_ANALYSIS_ERROR"
          message: "Failed to analyze performance"
