# AnalyzeCompetitive Power Automate Flow Definition
# Version: 1.0.0
# Agent: MKT (Marketing Strategy)
# Description: Assesses competitive landscape and identifies opportunities

name: AnalyzeCompetitive
description: >
  HTTP-triggered flow that analyzes the competitive landscape for marketing
  strategy development. Returns competitive matrix, positioning map,
  messaging analysis, and strategic opportunities.

trigger:
  type: HTTP
  method: POST
  schema:
    type: object
    required:
      - session_id
      - request_id
      - competitors
    properties:
      session_id:
        type: string
        format: uuid
      request_id:
        type: string
        format: uuid
      competitors:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            website:
              type: string
            market_position:
              type: string
      category:
        type: string
        description: Product/service category
      own_brand:
        type: object
        properties:
          name:
            type: string
          positioning:
            type: string
          key_differentiators:
            type: array
            items:
              type: string
      analysis_focus:
        type: array
        items:
          type: string
          enum: [messaging, visual_identity, channel_presence, pricing, product_features]

environment_variables:
  EAP_DATAVERSE_URL:
    description: EAP Dataverse environment URL
    required: true

steps:
  # Step 1: Parse input
  - id: parse_input
    type: Compose
    name: Parse Input
    inputs:
      session_id: "@triggerBody()?['session_id']"
      request_id: "@triggerBody()?['request_id']"
      competitors: "@triggerBody()?['competitors']"
      category: "@triggerBody()?['category']"
      own_brand: "@triggerBody()?['own_brand']"
      analysis_focus: "@coalesce(triggerBody()?['analysis_focus'], createArray('messaging', 'channel_presence', 'positioning'))"
      start_time: "@utcNow()"

  # Step 2: Build competitive profiles
  - id: build_profiles
    type: Compose
    name: Build Competitive Profiles
    inputs:
      competitor_profiles:
        - name: "Competitor A"
          market_position: "Market Leader"
          estimated_market_share: 35
          strengths:
            - "Strong brand recognition"
            - "Large customer base"
            - "Comprehensive product suite"
          weaknesses:
            - "Perceived as expensive"
            - "Slow to innovate"
            - "Complex implementation"
          positioning: "Enterprise solution for large organizations"
          key_messages:
            - "Trusted by Fortune 500"
            - "Complete enterprise platform"
          target_audience: "Large enterprises"
          pricing_tier: "Premium"
          channel_presence:
            paid_search: "heavy"
            paid_social: "moderate"
            content_marketing: "heavy"
            events: "heavy"
        - name: "Competitor B"
          market_position: "Challenger"
          estimated_market_share: 20
          strengths:
            - "Modern technology"
            - "Competitive pricing"
            - "Strong customer service"
          weaknesses:
            - "Limited enterprise features"
            - "Smaller partner ecosystem"
          positioning: "Modern solution for growing companies"
          key_messages:
            - "Built for the modern business"
            - "Simple yet powerful"
          target_audience: "Mid-market growth companies"
          pricing_tier: "Mid-range"
          channel_presence:
            paid_search: "heavy"
            paid_social: "heavy"
            content_marketing: "moderate"
            events: "light"
        - name: "Competitor C"
          market_position: "Niche Player"
          estimated_market_share: 10
          strengths:
            - "Deep specialization"
            - "Industry expertise"
            - "Personalized service"
          weaknesses:
            - "Limited scalability"
            - "Narrow feature set"
          positioning: "Specialist solution for specific industries"
          key_messages:
            - "Industry-specific expertise"
            - "Tailored for your needs"
          target_audience: "Industry-specific buyers"
          pricing_tier: "Variable"
          channel_presence:
            paid_search: "moderate"
            paid_social: "light"
            content_marketing: "heavy"
            events: "moderate"
    run_after: parse_input

  # Step 3: Create competitive matrix
  - id: create_matrix
    type: Compose
    name: Create Competitive Matrix
    inputs:
      comparison_dimensions:
        - dimension: "Market Presence"
          our_brand: 4
          competitor_a: 5
          competitor_b: 3
          competitor_c: 2
        - dimension: "Product Innovation"
          our_brand: 4
          competitor_a: 3
          competitor_b: 5
          competitor_c: 3
        - dimension: "Price Competitiveness"
          our_brand: 3
          competitor_a: 2
          competitor_b: 4
          competitor_c: 3
        - dimension: "Customer Service"
          our_brand: 5
          competitor_a: 3
          competitor_b: 4
          competitor_c: 5
        - dimension: "Ease of Use"
          our_brand: 4
          competitor_a: 2
          competitor_b: 5
          competitor_c: 3
        - dimension: "Enterprise Features"
          our_brand: 4
          competitor_a: 5
          competitor_b: 3
          competitor_c: 2
      overall_scores:
        our_brand: 24
        competitor_a: 20
        competitor_b: 24
        competitor_c: 18
      competitive_position: "Strong challenger with differentiation opportunity"
    run_after: build_profiles

  # Step 4: Analyze messaging landscape
  - id: analyze_messaging
    type: Compose
    name: Analyze Messaging Landscape
    inputs:
      messaging_analysis:
        common_themes:
          - theme: "Digital Transformation"
            prevalence: "high"
            our_usage: "moderate"
            differentiation_opportunity: "Execution expertise"
          - theme: "ROI/Business Outcomes"
            prevalence: "high"
            our_usage: "high"
            differentiation_opportunity: "Specific proof points"
          - theme: "Innovation"
            prevalence: "medium"
            our_usage: "low"
            differentiation_opportunity: "Technology leadership"
          - theme: "Simplicity"
            prevalence: "medium"
            our_usage: "high"
            differentiation_opportunity: "User experience"
        messaging_gaps:
          - gap: "Human element / partnership"
            opportunity: "Emphasize dedicated support and success partnership"
          - gap: "Speed to value"
            opportunity: "Highlight faster implementation and time to ROI"
          - gap: "Flexibility/customization"
            opportunity: "Showcase adaptable solutions"
        recommended_positioning:
          primary_position: "The trusted partner for business transformation"
          differentiation_pillars:
            - "Proven expertise (outcomes focus)"
            - "Dedicated partnership (human element)"
            - "Flexible solutions (customization)"
          avoid_competing_on:
            - "Lowest price"
            - "Feature count"
            - "Company size"
    run_after: create_matrix

  # Step 5: Identify opportunities
  - id: identify_opportunities
    type: Compose
    name: Identify Strategic Opportunities
    inputs:
      strategic_opportunities:
        - opportunity: "Differentiate on Customer Success"
          description: "No competitor strongly owns the 'partnership' positioning"
          tactics:
            - "Highlight dedicated success teams"
            - "Showcase customer testimonials"
            - "Emphasize long-term relationships"
          priority: "high"
          effort: "low"
        - opportunity: "Own Speed to Value"
          description: "Market leader perceived as slow; opportunity to position as agile"
          tactics:
            - "Publish implementation benchmarks"
            - "Create quick-start programs"
            - "Case studies on rapid deployments"
          priority: "high"
          effort: "medium"
        - opportunity: "Target Dissatisfied Enterprise Customers"
          description: "Competitor A customers frustrated with complexity and cost"
          tactics:
            - "Competitive switch campaigns"
            - "Migration support messaging"
            - "TCO comparison content"
          priority: "medium"
          effort: "medium"
        - opportunity: "Build Thought Leadership"
          description: "Gap in original industry insights and research"
          tactics:
            - "Publish original research"
            - "Industry benchmark reports"
            - "Expert webinar series"
          priority: "medium"
          effort: "high"
      threats_to_monitor:
        - threat: "Competitor B aggressive pricing"
          mitigation: "Emphasize value over price, total cost of ownership"
        - threat: "Competitor A product updates"
          mitigation: "Monitor releases, maintain feature parity on key areas"
        - threat: "New market entrants"
          mitigation: "Strengthen customer relationships, increase switching costs"
    run_after: analyze_messaging

  # Step 6: Build response
  - id: build_response
    type: Compose
    name: Build Response
    inputs:
      request_id: "@outputs('parse_input')?['request_id']"
      timestamp: "@utcNow()"
      source_agent: "MKT"
      status: "success"
      data:
        analysis_scope:
          category: "@outputs('parse_input')?['category']"
          competitors_analyzed: "@length(outputs('parse_input')?['competitors'])"
          focus_areas: "@outputs('parse_input')?['analysis_focus']"
        competitor_profiles: "@outputs('build_profiles')?['competitor_profiles']"
        competitive_matrix:
          dimensions: "@outputs('create_matrix')?['comparison_dimensions']"
          overall_scores: "@outputs('create_matrix')?['overall_scores']"
          competitive_position: "@outputs('create_matrix')?['competitive_position']"
        messaging_landscape:
          common_themes: "@outputs('analyze_messaging')?['messaging_analysis']?['common_themes']"
          messaging_gaps: "@outputs('analyze_messaging')?['messaging_analysis']?['messaging_gaps']"
          recommended_positioning: "@outputs('analyze_messaging')?['recommended_positioning']"
        strategic_opportunities: "@outputs('identify_opportunities')?['strategic_opportunities']"
        threats_to_monitor: "@outputs('identify_opportunities')?['threats_to_monitor']"
      confidence: "HIGH"
      sources:
        - "AGENT_KB"
        - "COMPETITIVE_ANALYSIS"
        - "MARKET_DATA"
      recommendations:
        - "Focus messaging on partnership and customer success"
        - "Develop competitive switch campaign for enterprise segment"
        - "Invest in thought leadership content"
      follow_up_questions:
        - "Would you like to develop a campaign strategy based on this analysis?"
        - "Should we create competitive battle cards?"
        - "Do you want detailed positioning recommendations?"
      metadata:
        processing_time_ms: "@div(sub(ticks(utcNow()), ticks(outputs('parse_input')?['start_time'])), 10000)"
    run_after: identify_opportunities

  # Step 7: Return response
  - id: return_response
    type: Response
    name: Return Response
    inputs:
      statusCode: 200
      headers:
        Content-Type: application/json
      body: "@outputs('build_response')"

error_handling:
  on_error:
    - id: return_error
      type: Response
      name: Return Error Response
      inputs:
        statusCode: 500
        headers:
          Content-Type: application/json
        body:
          request_id: "@outputs('parse_input')?['request_id']"
          source_agent: "MKT"
          error: true
          code: "COMPETITIVE_ANALYSIS_ERROR"
          message: "Failed to analyze competitive landscape"
