/**
 * Multi-Agent Architecture - Type Exports
 *
 * Central export point for all multi-agent type definitions.
 */

// Agent code definitions
export {
  AGENT_CODES,
  AGENT_NAMES,
  AGENT_DESCRIPTIONS,
  isValidAgentCode,
  getSpecialistCodes,
  type AgentCode,
} from './agent-codes.js';

// Session context types
export {
  WORKFLOW_GATES,
  getGateForStep,
  type SessionType,
  type ClientContext,
  type Objectives,
  type BudgetInfo,
  type AudienceStrategy,
  type AudienceSegment,
  type LTVTier,
  type ChannelAllocations,
  type ChannelAllocation,
  type ChannelConstraint,
  type PartnerSelections,
  type PartnerSelection,
  type SupplyPathAnalysis,
  type MeasurementFramework,
  type MetricDefinition,
  type OptimizationRules,
  type OptimizationRule,
  type ComplianceRequirements,
  type DocumentStatus,
  type PlanState,
  type SessionContext,
} from './session-context.js';

// Agent request types
export {
  type RequestOptions,
  type ConfidenceThreshold,
  type AgentRequest,
  type ANLRequestType,
  type ANLCalculateProjectionParams,
  type ANLRunScenarioParams,
  type ANLValidateStatisticsParams,
  type ANLCalculateLTVParams,
  type AUDRequestType,
  type AUDSegmentAudienceParams,
  type AUDBuildPersonaParams,
  type AUDRecommendTargetingParams,
  type AUDCalculateAudienceSizeParams,
  type CHARequestType,
  type CHARecommendChannelsParams,
  type CHACalculateAllocationParams,
  type CHALookupBenchmarksParams,
  type CHAEvaluateMixParams,
  type SPORequestType,
  type SPOAnalyzeSupplyPathParams,
  type SPOCalculateNBIParams,
  type SPOEvaluatePartnersParams,
  type DOCRequestType,
  type DOCGeneratePlanParams,
  type DOCGenerateBriefParams,
  type DOCGenerateSummaryParams,
  type DOCExportDocumentParams,
  type PRFRequestType,
  type PRFAnalyzePerformanceParams,
  type PRFDetectAnomaliesParams,
  type PRFExtractLearningsParams,
  type PRFRecommendOptimizationParams,
  isANLRequest,
  isAUDRequest,
  isCHARequest,
  isSPORequest,
  isDOCRequest,
  isPRFRequest,
} from './agent-request.js';

// Agent response types
export {
  type ConfidenceLevel,
  type DataSource,
  type AgentResponseMetadata,
  type AgentResponse,
  type AgentErrorResponse,
  type AgentErrorCode,
  type ANLProjectionResponse,
  type ANLScenarioResponse,
  type ANLStatisticsResponse,
  type AUDSegmentationResponse,
  type AUDPersonaResponse,
  type AUDTargetingResponse,
  type CHARecommendationResponse,
  type CHAAllocationResponse,
  type CHABenchmarkResponse,
  type SPOAnalysisResponse,
  type SPONBIResponse,
  type DOCGenerationResponse,
  type PRFAnalysisResponse,
  type PRFAnomalyResponse,
  type PRFLearningsResponse,
  type ORCRoutingDecision,
  type ORCSynthesizedResponse,
  isAgentResponse,
  isAgentError,
  isSuccessResponse,
} from './agent-response.js';
