# RequestSpecialistViaORC Power Automate Flow Definition
# Version: 1.0.0
# Agent: GHA (Growth Hacking Agent)
# Description: Routes specialist requests from GHA through ORC for agent coordination

name: RequestSpecialistViaORC
description: >
  HTTP-triggered flow that sends specialist requests from GHA to ORC for routing.
  GHA uses this flow when growth strategy development requires specialist analysis
  such as ANL for projections, AUD for segmentation, CHA for channels, or DOC for documentation.
  ORC routes the request to the appropriate specialist and returns the result to GHA.

trigger:
  type: HTTP
  method: POST
  schema:
    type: object
    required:
      - session_id
      - target_specialist
      - user_message
    properties:
      session_id:
        type: string
        format: uuid
        description: Main session identifier
      growth_session_id:
        type: string
        format: uuid
        description: Growth session identifier for context
      target_specialist:
        type: string
        enum:
          - ANL
          - AUD
          - CHA
          - DOC
          - PRF
          - MKT
          - CST
        description: Target specialist agent code
      user_message:
        type: string
        description: The specific request for the specialist
      request_type:
        type: string
        enum:
          - projection
          - segmentation
          - channel_recommendation
          - documentation
          - performance_analysis
          - marketing_strategy
          - strategic_framework
        description: Type of specialist request
      growth_context:
        type: object
        description: Growth plan context to pass to the specialist
        properties:
          growth_workflow_step:
            type: integer
          growth_workflow_gate:
            type: integer
          north_star_metric:
            type: object
          priority_stages:
            type: array
          growth_plan_state:
            type: object
      urgency:
        type: string
        enum:
          - normal
          - high
        default: normal
        description: Request urgency level

environment_variables:
  EAP_DATAVERSE_URL:
    description: EAP Dataverse environment URL
    required: true
  ORC_ENDPOINT_URL:
    description: ORC RouteToSpecialist flow endpoint URL
    required: true

steps:
  # Step 1: Parse input
  - id: parse_input
    type: Compose
    name: Parse Input
    inputs:
      session_id: "@triggerBody()?['session_id']"
      growth_session_id: "@triggerBody()?['growth_session_id']"
      target_specialist: "@triggerBody()?['target_specialist']"
      user_message: "@triggerBody()?['user_message']"
      request_type: "@triggerBody()?['request_type']"
      growth_context: "@triggerBody()?['growth_context']"
      urgency: "@coalesce(triggerBody()?['urgency'], 'normal')"
      request_id: "@guid()"
      request_timestamp: "@utcNow()"

  # Step 2: Get current growth state if not provided
  - id: check_growth_context_provided
    type: Condition
    name: Growth Context Provided?
    expression:
      not:
        empty:
          - "@outputs('parse_input')?['growth_context']"
    run_after: parse_input

  # Step 2a: Get growth state from Dataverse
  - id: get_growth_state
    type: HTTP
    name: Get Current Growth State
    condition: check_growth_context_provided.false
    inputs:
      method: GET
      uri: "@if(empty(outputs('parse_input')?['growth_session_id']), concat(variables('EAP_DATAVERSE_URL'), '/api/data/v9.2/eap_growth_sessions?$filter=eap_session_id eq ''', outputs('parse_input')?['session_id'], ''''), concat(variables('EAP_DATAVERSE_URL'), '/api/data/v9.2/eap_growth_sessions(', outputs('parse_input')?['growth_session_id'], ')'))"
      headers:
        Authorization: "Bearer @{body('Get_Access_Token')?['access_token']}"
        Content-Type: application/json
    run_after: check_growth_context_provided

  # Step 2b: Parse retrieved growth state
  - id: parse_growth_state
    type: Compose
    name: Parse Retrieved Growth State
    condition: check_growth_context_provided.false
    inputs:
      growth_workflow_step: "@coalesce(body('get_growth_state')?['eap_growth_workflow_step'], first(body('get_growth_state')?['value'])?['eap_growth_workflow_step'], 1)"
      growth_workflow_gate: "@coalesce(body('get_growth_state')?['eap_growth_workflow_gate'], first(body('get_growth_state')?['value'])?['eap_growth_workflow_gate'], 0)"
      north_star_metric: "@coalesce(body('get_growth_state')?['eap_north_star_metric'], first(body('get_growth_state')?['value'])?['eap_north_star_metric'])"
      priority_stages: "@json(coalesce(body('get_growth_state')?['eap_priority_stages'], first(body('get_growth_state')?['value'])?['eap_priority_stages'], '[]'))"
      growth_plan_state: "@json(coalesce(body('get_growth_state')?['eap_growth_plan_state'], first(body('get_growth_state')?['value'])?['eap_growth_plan_state'], '{}'))"
    run_after: get_growth_state

  # Step 3: Build growth context for specialist
  - id: build_growth_context
    type: Compose
    name: Build Growth Context for Specialist
    inputs:
      growth_session_id: "@outputs('parse_input')?['growth_session_id']"
      growth_workflow_step: "@coalesce(outputs('parse_input')?['growth_context']?['growth_workflow_step'], outputs('parse_growth_state')?['growth_workflow_step'])"
      growth_workflow_gate: "@coalesce(outputs('parse_input')?['growth_context']?['growth_workflow_gate'], outputs('parse_growth_state')?['growth_workflow_gate'])"
      north_star_metric: "@coalesce(outputs('parse_input')?['growth_context']?['north_star_metric'], outputs('parse_growth_state')?['north_star_metric'])"
      priority_stages: "@coalesce(outputs('parse_input')?['growth_context']?['priority_stages'], outputs('parse_growth_state')?['priority_stages'])"
      growth_plan_state: "@coalesce(outputs('parse_input')?['growth_context']?['growth_plan_state'], outputs('parse_growth_state')?['growth_plan_state'])"
      requesting_step_name: "@if(equals(outputs('parse_input')?['growth_context']?['growth_workflow_step'], 1), 'Growth Context', if(equals(outputs('parse_input')?['growth_context']?['growth_workflow_step'], 2), 'North Star Definition', if(equals(outputs('parse_input')?['growth_context']?['growth_workflow_step'], 3), 'Lifecycle Analysis', if(equals(outputs('parse_input')?['growth_context']?['growth_workflow_step'], 4), 'Audience Strategy', if(equals(outputs('parse_input')?['growth_context']?['growth_workflow_step'], 5), 'Tactics Development', if(equals(outputs('parse_input')?['growth_context']?['growth_workflow_step'], 6), 'Channel Strategy', if(equals(outputs('parse_input')?['growth_context']?['growth_workflow_step'], 7), 'Projections', 'Growth Plan Documentation')))))))"
    run_after:
      - check_growth_context_provided
      - parse_growth_state

  # Step 4: Log outgoing specialist request
  - id: log_outgoing_request
    type: HTTP
    name: Log Outgoing Specialist Request
    inputs:
      method: POST
      uri: "@{variables('EAP_DATAVERSE_URL')}/api/data/v9.2/eap_routing_logs"
      headers:
        Authorization: "Bearer @{body('Get_Access_Token')?['access_token']}"
        Content-Type: application/json
      body:
        eap_entry_id: "@outputs('parse_input')?['request_id']"
        eap_session_id: "@outputs('parse_input')?['session_id']"
        eap_source_agent: "GHA"
        eap_target_agent: "@outputs('parse_input')?['target_specialist']"
        eap_routing_status: "pending"
        eap_user_message: "@outputs('parse_input')?['user_message']"
        eap_request_type: "@outputs('parse_input')?['request_type']"
        eap_context_json: "@string(outputs('build_growth_context'))"
    run_after: build_growth_context

  # Step 5: Build ORC request payload
  - id: build_orc_request
    type: Compose
    name: Build ORC Request Payload
    inputs:
      session_id: "@outputs('parse_input')?['session_id']"
      user_message: "@outputs('parse_input')?['user_message']"
      source_agent: "GHA"
      target_specialist: "@outputs('parse_input')?['target_specialist']"
      growth_context: "@outputs('build_growth_context')"
      request_metadata:
        request_id: "@outputs('parse_input')?['request_id']"
        request_type: "@outputs('parse_input')?['request_type']"
        urgency: "@outputs('parse_input')?['urgency']"
        timestamp: "@outputs('parse_input')?['request_timestamp']"
    run_after: log_outgoing_request

  # Step 6: Send request to ORC RouteToSpecialist
  - id: call_orc_route
    type: HTTP
    name: Call ORC RouteToSpecialist
    inputs:
      method: POST
      uri: "@{variables('ORC_ENDPOINT_URL')}"
      headers:
        Content-Type: application/json
      body: "@outputs('build_orc_request')"
      timeout: PT45S
    run_after: build_orc_request

  # Step 7: Check ORC response status
  - id: check_orc_response
    type: Condition
    name: ORC Response Success?
    expression:
      and:
        - equals:
            - "@outputs('call_orc_route')?['statusCode']"
            - 200
        - not:
            equals:
              - "@body('call_orc_route')?['error']"
              - true
    run_after: call_orc_route

  # Step 7a: Success - Parse specialist response
  - id: parse_specialist_response
    type: Compose
    name: Parse Specialist Response
    condition: check_orc_response.true
    inputs:
      specialist_code: "@outputs('parse_input')?['target_specialist']"
      specialist_response: "@body('call_orc_route')?['specialist_response']"
      confidence_score: "@body('call_orc_route')?['confidence_score']"
      response_metadata: "@body('call_orc_route')?['metadata']"
    run_after: check_orc_response

  # Step 7b: Failure - Build error response
  - id: build_error_response
    type: Compose
    name: Build Error Response
    condition: check_orc_response.false
    inputs:
      error: true
      error_code: "@coalesce(body('call_orc_route')?['code'], 'SPECIALIST_ERROR')"
      error_message: "@coalesce(body('call_orc_route')?['message'], 'Specialist request failed')"
      target_specialist: "@outputs('parse_input')?['target_specialist']"
      request_id: "@outputs('parse_input')?['request_id']"
      fallback_suggestion: "@if(equals(outputs('parse_input')?['target_specialist'], 'ANL'), 'GHA can provide simplified projections without ANL', if(equals(outputs('parse_input')?['target_specialist'], 'AUD'), 'GHA can suggest basic segmentation approach', if(equals(outputs('parse_input')?['target_specialist'], 'CHA'), 'GHA can recommend growth channels based on frameworks', 'Retry the request or proceed without specialist input')))"
    run_after: check_orc_response

  # Step 8: Update routing log with result
  - id: update_routing_log
    type: HTTP
    name: Update Routing Log
    inputs:
      method: PATCH
      uri: "@{variables('EAP_DATAVERSE_URL')}/api/data/v9.2/eap_routing_logs(@{outputs('parse_input')?['request_id']})"
      headers:
        Authorization: "Bearer @{body('Get_Access_Token')?['access_token']}"
        Content-Type: application/json
      body:
        eap_routing_status: "@if(outputs('check_orc_response'), 'completed', 'failed')"
        eap_response_json: "@string(coalesce(outputs('parse_specialist_response'), outputs('build_error_response')))"
        eap_response_timestamp: "@utcNow()"
    run_after:
      - parse_specialist_response
      - build_error_response

  # Step 9: Build final response for GHA
  - id: build_final_response
    type: Compose
    name: Build Final Response
    inputs:
      success: "@outputs('check_orc_response')"
      request_id: "@outputs('parse_input')?['request_id']"
      target_specialist: "@outputs('parse_input')?['target_specialist']"
      specialist_response: "@if(outputs('check_orc_response'), outputs('parse_specialist_response')?['specialist_response'], null)"
      confidence_score: "@if(outputs('check_orc_response'), outputs('parse_specialist_response')?['confidence_score'], null)"
      error: "@if(not(outputs('check_orc_response')), outputs('build_error_response'), null)"
      integration_guidance:
        should_update_state: "@outputs('check_orc_response')"
        state_field_to_update: "@if(equals(outputs('parse_input')?['target_specialist'], 'ANL'), 'projections', if(equals(outputs('parse_input')?['target_specialist'], 'AUD'), 'audience_segments', if(equals(outputs('parse_input')?['target_specialist'], 'CHA'), 'channel_strategy', if(equals(outputs('parse_input')?['target_specialist'], 'DOC'), 'growth_plan_document', 'specialist_outputs'))))"
        next_step_suggestion: "@if(equals(outputs('parse_input')?['target_specialist'], 'ANL'), 'Proceed to Step 8 Documentation', if(equals(outputs('parse_input')?['target_specialist'], 'AUD'), 'Proceed to Step 5 Tactics Development', if(equals(outputs('parse_input')?['target_specialist'], 'CHA'), 'Proceed to Step 7 Projections', if(equals(outputs('parse_input')?['target_specialist'], 'DOC'), 'Growth plan complete - offer handoff', 'Continue with current step'))))"
      timestamp: "@utcNow()"
    run_after: update_routing_log

  # Step 10: Return response
  - id: return_response
    type: Response
    name: Return Response
    inputs:
      statusCode: "@if(outputs('check_orc_response'), 200, 502)"
      headers:
        Content-Type: application/json
      body: "@outputs('build_final_response')"

error_handling:
  on_error:
    - id: log_error
      type: HTTP
      name: Log Error
      inputs:
        method: PATCH
        uri: "@{variables('EAP_DATAVERSE_URL')}/api/data/v9.2/eap_routing_logs(@{outputs('parse_input')?['request_id']})"
        headers:
          Authorization: "Bearer @{body('Get_Access_Token')?['access_token']}"
          Content-Type: application/json
        body:
          eap_routing_status: "error"
          eap_error_message: "Flow execution error"

    - id: return_error
      type: Response
      name: Return Error Response
      inputs:
        statusCode: 500
        headers:
          Content-Type: application/json
        body:
          success: false
          error: true
          code: "INTERNAL_ERROR"
          message: "Failed to process specialist request"
          request_id: "@outputs('parse_input')?['request_id']"
          target_specialist: "@outputs('parse_input')?['target_specialist']"
