# DOCS_Check_Content_Access Power Automate Flow Definition
# Version: 7.0.0
# Agent: DOCS (Documentation)
# Description: Verify user permissions for protected documentation content

name: DOCS_Check_Content_Access
description: >
  HTTP-triggered flow that verifies user permissions for accessing protected
  documentation content. Queries user profile and access rules from Dataverse
  to determine authorization.

trigger:
  type: HTTP
  method: POST
  schema:
    type: object
    required:
      - session_id
      - user_id
      - content_identifier
    properties:
      session_id:
        type: string
        format: uuid
      user_id:
        type: string
        description: Microsoft Directory user identifier
      content_identifier:
        type: string
        description: Document identifier being requested

environment_variables:
  EAP_DATAVERSE_URL:
    description: EAP Dataverse environment URL
    required: true

steps:
  # Step 1: Parse input
  - id: parse_input
    type: Compose
    name: Parse Input
    inputs:
      session_id: "@triggerBody()?['session_id']"
      user_id: "@triggerBody()?['user_id']"
      content_identifier: "@triggerBody()?['content_identifier']"
      timestamp: "@utcNow()"

  # Step 2: Retrieve user profile from Dataverse
  - id: get_user_profile
    type: OpenApiConnection
    name: Get User Profile
    inputs:
      host:
        connectionName: shared_commondataserviceforapps
        operationId: ListRecords
        apiId: /providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps
      parameters:
        entityName: eap_user_profile
        $filter: "eap_user_id eq '@{outputs('parse_input')?['user_id']}'"
        $top: 1
      authentication: "@parameters('$authentication')"
    run_after: parse_input

  # Step 3: Check if user profile exists
  - id: check_profile_exists
    type: Condition
    name: Check Profile Exists
    expression:
      and:
        - greater:
            - "@length(outputs('get_user_profile')?['body/value'])"
            - 0
    if_true:
      next_step: lookup_access_rule
    if_false:
      next_step: return_profile_not_found
    run_after: get_user_profile

  # Step 4: Lookup content access rule
  - id: lookup_access_rule
    type: OpenApiConnection
    name: Lookup Access Rule
    inputs:
      host:
        connectionName: shared_commondataserviceforapps
        operationId: ListRecords
        apiId: /providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps
      parameters:
        entityName: eap_access_rule
        $filter: "eap_content_identifier eq '@{outputs('parse_input')?['content_identifier']}' and eap_rule_active eq true"
        $top: 1
      authentication: "@parameters('$authentication')"
    run_after: check_profile_exists

  # Step 5: Evaluate access conditions
  - id: evaluate_access
    type: Compose
    name: Evaluate Access Conditions
    inputs:
      has_rule: "@greater(length(outputs('lookup_access_rule')?['body/value']), 0)"
      user_profile: "@first(outputs('get_user_profile')?['body/value'])"
      access_rule: "@if(greater(length(outputs('lookup_access_rule')?['body/value']), 0), first(outputs('lookup_access_rule')?['body/value']), null)"
      access_granted: "@or(equals(length(outputs('lookup_access_rule')?['body/value']), 0), true)"
    run_after: lookup_access_rule

  # Step 6: Build success response
  - id: build_success_response
    type: Compose
    name: Build Success Response
    inputs:
      session_id: "@outputs('parse_input')?['session_id']"
      user_id: "@outputs('parse_input')?['user_id']"
      content_identifier: "@outputs('parse_input')?['content_identifier']"
      access_granted: "@outputs('evaluate_access')?['access_granted']"
      content_authorized: "@outputs('evaluate_access')?['access_granted']"
      rule_matched: "@if(outputs('evaluate_access')?['has_rule'], outputs('evaluate_access')?['access_rule']?['eap_rule_id'], 'NO_RULE')"
      denial_message: "@if(outputs('evaluate_access')?['access_granted'], null, 'This content requires specific access permissions based on your role in the organization. To request access say request access and I will help submit your request to the Platform team.')"
      timestamp: "@outputs('parse_input')?['timestamp']"
    run_after: evaluate_access

  # Step 7: Return success response
  - id: return_success
    type: Response
    name: Return Success Response
    inputs:
      statusCode: 200
      headers:
        Content-Type: application/json
      body: "@outputs('build_success_response')"
    run_after: build_success_response

  # Profile not found response
  - id: return_profile_not_found
    type: Response
    name: Return Profile Not Found
    inputs:
      statusCode: 200
      headers:
        Content-Type: application/json
      body:
        session_id: "@outputs('parse_input')?['session_id']"
        user_id: "@outputs('parse_input')?['user_id']"
        content_identifier: "@outputs('parse_input')?['content_identifier']"
        access_granted: false
        content_authorized: false
        denial_message: "Unable to verify your access level. Please try again or contact support."
        rule_matched: "PROFILE_NOT_FOUND"
        timestamp: "@outputs('parse_input')?['timestamp']"

error_handling:
  on_error:
    - id: return_error
      type: Response
      name: Return Error Response
      inputs:
        statusCode: 200
        headers:
          Content-Type: application/json
        body:
          session_id: "@outputs('parse_input')?['session_id']"
          user_id: "@outputs('parse_input')?['user_id']"
          content_identifier: "@outputs('parse_input')?['content_identifier']"
          access_granted: false
          content_authorized: false
          denial_message: "Unable to verify content permissions at this time."
          rule_matched: "EVALUATION_ERROR"
          error: true
