# LookupBenchmarks Power Automate Flow Definition
# Version: 1.0.0
# Agent: CHA (Channel Strategy)
# Description: Retrieves industry and channel benchmarks for media planning

name: LookupBenchmarks
description: >
  HTTP-triggered flow that retrieves performance benchmarks by channel,
  industry vertical, and metric type. Returns contextual benchmarks with
  percentile rankings and source attribution.

trigger:
  type: HTTP
  method: POST
  schema:
    type: object
    required:
      - session_id
      - request_id
      - channels
    properties:
      session_id:
        type: string
        format: uuid
      request_id:
        type: string
        format: uuid
      channels:
        type: array
        items:
          type: string
        description: Channel IDs to look up benchmarks for
      industry:
        type: string
        description: Industry vertical for contextualized benchmarks
      metrics:
        type: array
        items:
          type: string
        description: Specific metrics to retrieve
        default: [cpm, ctr, cpc, conversion_rate, roas]
      market:
        type: string
        description: Geographic market
        default: US
      campaign_type:
        type: string
        enum: [awareness, consideration, conversion, retention]

environment_variables:
  EAP_DATAVERSE_URL:
    description: EAP Dataverse environment URL
    required: true
  BENCHMARK_API_URL:
    description: External benchmark data API (optional)
    required: false

steps:
  # Step 1: Parse input
  - id: parse_input
    type: Compose
    name: Parse Input
    inputs:
      session_id: "@triggerBody()?['session_id']"
      request_id: "@triggerBody()?['request_id']"
      channels: "@triggerBody()?['channels']"
      industry: "@coalesce(triggerBody()?['industry'], 'general')"
      metrics: "@coalesce(triggerBody()?['metrics'], createArray('cpm', 'ctr', 'cpc', 'conversion_rate', 'roas'))"
      market: "@coalesce(triggerBody()?['market'], 'US')"
      campaign_type: "@triggerBody()?['campaign_type']"
      start_time: "@utcNow()"

  # Step 2: Load channel benchmark data
  - id: load_benchmarks
    type: Compose
    name: Load Channel Benchmarks
    inputs:
      benchmark_data:
        meta_facebook:
          channel_name: "Meta (Facebook/Instagram)"
          metrics:
            cpm:
              value: 12.50
              percentile_25: 8.00
              percentile_50: 12.50
              percentile_75: 18.00
              percentile_90: 28.00
            ctr:
              value: 0.90
              percentile_25: 0.50
              percentile_50: 0.90
              percentile_75: 1.40
              percentile_90: 2.10
            cpc:
              value: 1.38
              percentile_25: 0.80
              percentile_50: 1.38
              percentile_75: 2.20
              percentile_90: 3.50
            conversion_rate:
              value: 2.50
              percentile_25: 1.20
              percentile_50: 2.50
              percentile_75: 4.00
              percentile_90: 6.50
            roas:
              value: 3.80
              percentile_25: 2.00
              percentile_50: 3.80
              percentile_75: 6.00
              percentile_90: 10.00
          source: "Meta Business Suite Benchmarks 2026"

        google_search:
          channel_name: "Google Search"
          metrics:
            cpm:
              value: 38.00
              percentile_25: 22.00
              percentile_50: 38.00
              percentile_75: 55.00
              percentile_90: 85.00
            ctr:
              value: 3.50
              percentile_25: 1.80
              percentile_50: 3.50
              percentile_75: 5.50
              percentile_90: 8.00
            cpc:
              value: 2.69
              percentile_25: 1.20
              percentile_50: 2.69
              percentile_75: 4.50
              percentile_90: 8.00
            conversion_rate:
              value: 4.40
              percentile_25: 2.00
              percentile_50: 4.40
              percentile_75: 7.00
              percentile_90: 12.00
            roas:
              value: 5.50
              percentile_25: 2.50
              percentile_50: 5.50
              percentile_75: 9.00
              percentile_90: 15.00
          source: "Google Ads Benchmark Report 2026"

        google_display:
          channel_name: "Google Display Network"
          metrics:
            cpm:
              value: 3.50
              percentile_25: 1.50
              percentile_50: 3.50
              percentile_75: 6.00
              percentile_90: 12.00
            ctr:
              value: 0.35
              percentile_25: 0.15
              percentile_50: 0.35
              percentile_75: 0.60
              percentile_90: 1.00
            cpc:
              value: 0.75
              percentile_25: 0.35
              percentile_50: 0.75
              percentile_75: 1.40
              percentile_90: 2.50
            conversion_rate:
              value: 0.80
              percentile_25: 0.30
              percentile_50: 0.80
              percentile_75: 1.50
              percentile_90: 3.00
            roas:
              value: 2.20
              percentile_25: 1.00
              percentile_50: 2.20
              percentile_75: 4.00
              percentile_90: 7.00
          source: "Google Ads Benchmark Report 2026"

        youtube:
          channel_name: "YouTube"
          metrics:
            cpm:
              value: 9.50
              percentile_25: 5.00
              percentile_50: 9.50
              percentile_75: 16.00
              percentile_90: 28.00
            ctr:
              value: 0.65
              percentile_25: 0.30
              percentile_50: 0.65
              percentile_75: 1.10
              percentile_90: 2.00
            cpv:
              value: 0.08
              percentile_25: 0.03
              percentile_50: 0.08
              percentile_75: 0.15
              percentile_90: 0.25
            view_rate:
              value: 31.00
              percentile_25: 18.00
              percentile_50: 31.00
              percentile_75: 45.00
              percentile_90: 60.00
          source: "YouTube Ads Benchmarks 2026"

        tiktok:
          channel_name: "TikTok"
          metrics:
            cpm:
              value: 10.00
              percentile_25: 5.50
              percentile_50: 10.00
              percentile_75: 16.00
              percentile_90: 25.00
            ctr:
              value: 1.20
              percentile_25: 0.60
              percentile_50: 1.20
              percentile_75: 2.00
              percentile_90: 3.50
            cpc:
              value: 0.83
              percentile_25: 0.40
              percentile_50: 0.83
              percentile_75: 1.50
              percentile_90: 2.80
            conversion_rate:
              value: 1.80
              percentile_25: 0.80
              percentile_50: 1.80
              percentile_75: 3.20
              percentile_90: 5.50
          source: "TikTok For Business Benchmarks 2026"

        programmatic_display:
          channel_name: "Programmatic Display"
          metrics:
            cpm:
              value: 4.20
              percentile_25: 2.00
              percentile_50: 4.20
              percentile_75: 7.50
              percentile_90: 14.00
            ctr:
              value: 0.10
              percentile_25: 0.05
              percentile_50: 0.10
              percentile_75: 0.18
              percentile_90: 0.35
            viewability:
              value: 68.00
              percentile_25: 55.00
              percentile_50: 68.00
              percentile_75: 78.00
              percentile_90: 88.00
          source: "IAB Programmatic Benchmark Report 2026"

        ctv:
          channel_name: "Connected TV"
          metrics:
            cpm:
              value: 32.00
              percentile_25: 18.00
              percentile_50: 32.00
              percentile_75: 48.00
              percentile_90: 75.00
            completion_rate:
              value: 95.00
              percentile_25: 88.00
              percentile_50: 95.00
              percentile_75: 98.00
              percentile_90: 99.00
            reach_efficiency:
              value: 0.85
              percentile_25: 0.70
              percentile_50: 0.85
              percentile_75: 0.92
              percentile_90: 0.97
          source: "CTV Advertising Benchmark Study 2026"

        linear_tv:
          channel_name: "Linear TV"
          metrics:
            cpm:
              value: 18.00
              percentile_25: 10.00
              percentile_50: 18.00
              percentile_75: 30.00
              percentile_90: 50.00
            reach_percentage:
              value: 45.00
              percentile_25: 25.00
              percentile_50: 45.00
              percentile_75: 65.00
              percentile_90: 80.00
          source: "Nielsen TV Benchmark Data 2026"
    run_after: parse_input

  # Step 3: Filter to requested channels
  - id: filter_channels
    type: Select
    name: Filter Requested Channels
    inputs:
      from: "@outputs('parse_input')?['channels']"
      select:
        channel_id: "@item()"
        benchmark_data: "@outputs('load_benchmarks')?['benchmark_data']?[item()]"
        has_data: "@not(equals(outputs('load_benchmarks')?['benchmark_data']?[item()], null))"
    run_after: load_benchmarks

  # Step 4: Apply industry adjustments
  - id: apply_industry_adjustment
    type: Compose
    name: Apply Industry Adjustments
    inputs:
      industry: "@outputs('parse_input')?['industry']"
      adjustments:
        e_commerce:
          cpm_multiplier: 1.1
          conversion_rate_multiplier: 1.3
          roas_multiplier: 1.2
        financial_services:
          cpm_multiplier: 1.5
          conversion_rate_multiplier: 0.7
          cpc_multiplier: 2.0
        healthcare:
          cpm_multiplier: 1.3
          ctr_multiplier: 0.8
          conversion_rate_multiplier: 0.6
        travel:
          cpm_multiplier: 0.9
          ctr_multiplier: 1.2
          roas_multiplier: 1.1
        automotive:
          cpm_multiplier: 1.4
          ctr_multiplier: 0.9
          conversion_rate_multiplier: 0.5
        technology:
          cpm_multiplier: 1.2
          ctr_multiplier: 1.1
          roas_multiplier: 1.3
        retail:
          cpm_multiplier: 1.0
          conversion_rate_multiplier: 1.2
          roas_multiplier: 1.1
    run_after: filter_channels

  # Step 5: Build response
  - id: build_response
    type: Compose
    name: Build Response
    inputs:
      request_id: "@outputs('parse_input')?['request_id']"
      timestamp: "@utcNow()"
      source_agent: "CHA"
      status: "success"
      data:
        benchmarks: "@body('filter_channels')"
        industry: "@outputs('parse_input')?['industry']"
        industry_adjustments: "@outputs('apply_industry_adjustment')?['adjustments']?[outputs('parse_input')?['industry']]"
        market: "@outputs('parse_input')?['market']"
        benchmark_date: "2026-01"
        data_freshness: "Monthly update"
      confidence: "HIGH"
      sources:
        - "BENCHMARK_DATA"
        - "AGENT_KB"
      recommendations:
        - "Use median (50th percentile) for planning projections"
        - "Target 75th percentile for optimized campaigns"
        - "Benchmark against your own historical data when available"
      metadata:
        processing_time_ms: "@div(sub(ticks(utcNow()), ticks(outputs('parse_input')?['start_time'])), 10000)"
        channels_requested: "@length(outputs('parse_input')?['channels'])"
        channels_found: "@length(body('filter_channels'))"
    run_after: apply_industry_adjustment

  # Step 6: Return response
  - id: return_response
    type: Response
    name: Return Response
    inputs:
      statusCode: 200
      headers:
        Content-Type: application/json
      body: "@outputs('build_response')"

error_handling:
  on_error:
    - id: return_error
      type: Response
      name: Return Error Response
      inputs:
        statusCode: 500
        headers:
          Content-Type: application/json
        body:
          request_id: "@outputs('parse_input')?['request_id']"
          source_agent: "CHA"
          error: true
          code: "BENCHMARK_ERROR"
          message: "Failed to retrieve benchmarks"
