/**
 * Pre-built Workflow Trees
 */

export { MPA_WORKFLOW_TREES, MPA_BUDGET_OPTIMIZATION, MPA_CAMPAIGN_PLANNING, MPA_PERFORMANCE_ANALYSIS, getMPATree } from './mpa-workflows';
export { CA_WORKFLOW_TREES, CA_CREATIVE_BRIEF, CA_ASSET_PRODUCTION, CA_CAMPAIGN_LAUNCH, CA_CLIENT_REPORTING, getCATree } from './ca-workflows';
