# GetSessionState Power Automate Flow Definition
# Version: 1.0.0
# Agent: ORC (Orchestrator)
# Description: Retrieves current session state and plan data from EAP

name: GetSessionState
description: >
  HTTP-triggered flow that retrieves the current session state from EAP Dataverse.
  Returns the full session context including workflow step, gate, and plan state.
  Used by Copilot Studio to provide context-aware responses.

trigger:
  type: HTTP
  method: GET
  schema:
    type: object
    required:
      - session_id
    properties:
      session_id:
        type: string
        format: uuid
        description: Session identifier to retrieve
      include_history:
        type: boolean
        default: false
        description: Include conversation history summary
      include_audit:
        type: boolean
        default: false
        description: Include recent audit logs

environment_variables:
  EAP_DATAVERSE_URL:
    description: EAP Dataverse environment URL
    required: true

steps:
  # Step 1: Parse input parameters
  - id: parse_input
    type: Compose
    name: Parse Input
    inputs:
      session_id: "@triggerBody()?['session_id']"
      include_history: "@coalesce(triggerBody()?['include_history'], false)"
      include_audit: "@coalesce(triggerBody()?['include_audit'], false)"
      request_timestamp: "@utcNow()"

  # Step 2: Get session from Dataverse
  - id: get_session
    type: HTTP
    name: Get Session from Dataverse
    inputs:
      method: GET
      uri: "@{variables('EAP_DATAVERSE_URL')}/api/data/v9.2/eap_sessions(@{outputs('parse_input')?['session_id']})"
      headers:
        Authorization: "Bearer @{body('Get_Access_Token')?['access_token']}"
        Content-Type: application/json
        Prefer: "odata.include-annotations=*"
    run_after: parse_input

  # Step 3: Check if session exists
  - id: check_session_exists
    type: Condition
    name: Session Exists?
    expression:
      not:
        equals:
          - "@outputs('get_session')?['statusCode']"
          - 404
    run_after: get_session

  # Step 4a: Session exists - Parse session data
  - id: parse_session
    type: Compose
    name: Parse Session Data
    condition: check_session_exists.true
    inputs:
      session_id: "@body('get_session')?['eap_sessionid']"
      workflow_step: "@body('get_session')?['eap_workflow_step']"
      workflow_gate: "@body('get_session')?['eap_workflow_gate']"
      session_type: "@body('get_session')?['eap_session_type']"
      plan_state: "@json(coalesce(body('get_session')?['eap_plan_state'], '{}'))"
      created_at: "@body('get_session')?['createdon']"
      updated_at: "@body('get_session')?['modifiedon']"
      conversation_history_summary: "@body('get_session')?['eap_conversation_summary']"
    run_after: check_session_exists

  # Step 5: Get workflow gate details
  - id: get_gate_details
    type: Compose
    name: Get Workflow Gate Details
    condition: check_session_exists.true
    inputs:
      gate_number: "@outputs('parse_session')?['workflow_gate']"
      gate_name: "@if(equals(outputs('parse_session')?['workflow_gate'], 0), 'Initialization', if(equals(outputs('parse_session')?['workflow_gate'], 1), 'Foundation', if(equals(outputs('parse_session')?['workflow_gate'], 2), 'Strategy', if(equals(outputs('parse_session')?['workflow_gate'], 3), 'Execution', 'Documentation'))))"
      gate_steps:
        - gate: 0
          steps: [1]
          name: "Initialization"
        - gate: 1
          steps: [2, 3]
          name: "Foundation"
        - gate: 2
          steps: [4, 5, 6]
          name: "Strategy"
        - gate: 3
          steps: [7, 8, 9]
          name: "Execution"
        - gate: 4
          steps: [10]
          name: "Documentation"
    run_after: parse_session

  # Step 6: Calculate completion status
  - id: calculate_completion
    type: Compose
    name: Calculate Completion Status
    condition: check_session_exists.true
    inputs:
      current_step: "@outputs('parse_session')?['workflow_step']"
      total_steps: 10
      completion_percentage: "@mul(div(outputs('parse_session')?['workflow_step'], 10), 100)"
      steps_completed: "@sub(outputs('parse_session')?['workflow_step'], 1)"
      steps_remaining: "@sub(10, outputs('parse_session')?['workflow_step'])"
      plan_state_fields_populated: "@length(intersection(createArray('client_context', 'objectives', 'budget', 'audience', 'channels', 'partners', 'measurement', 'optimization', 'compliance', 'document'), json(coalesce(body('get_session')?['eap_plan_state'], '{}'))))"
    run_after: get_gate_details

  # Step 7: Condition - Include audit logs
  - id: check_include_audit
    type: Condition
    name: Include Audit Logs?
    condition: check_session_exists.true
    expression:
      equals:
        - "@outputs('parse_input')?['include_audit']"
        - true
    run_after: calculate_completion

  # Step 8a: Get recent routing logs
  - id: get_routing_logs
    type: HTTP
    name: Get Recent Routing Logs
    condition: check_include_audit.true
    inputs:
      method: GET
      uri: "@{variables('EAP_DATAVERSE_URL')}/api/data/v9.2/eap_routing_logs?$filter=eap_session_id eq '@{outputs('parse_input')?['session_id']}'&$orderby=createdon desc&$top=10"
      headers:
        Authorization: "Bearer @{body('Get_Access_Token')?['access_token']}"
        Content-Type: application/json
    run_after: check_include_audit

  # Step 9: Build audit summary
  - id: build_audit_summary
    type: Compose
    name: Build Audit Summary
    condition: check_include_audit.true
    inputs:
      recent_routes: "@body('get_routing_logs')?['value']"
      route_count: "@length(body('get_routing_logs')?['value'])"
      agents_consulted: "@union(body('get_routing_logs')?['value'], 'eap_target_agent')"
    run_after: get_routing_logs

  # Step 10: Build full response
  - id: build_response
    type: Compose
    name: Build Full Response
    condition: check_session_exists.true
    inputs:
      session_context: "@outputs('parse_session')"
      workflow_details:
        current_gate: "@outputs('get_gate_details')"
        completion: "@outputs('calculate_completion')"
      audit_summary: "@if(outputs('parse_input')?['include_audit'], outputs('build_audit_summary'), null)"
      metadata:
        retrieved_at: "@utcNow()"
        request_session_id: "@outputs('parse_input')?['session_id']"
    run_after:
      - calculate_completion
      - build_audit_summary

  # Step 4b: Session not found - Build error response
  - id: build_not_found_response
    type: Compose
    name: Build Not Found Response
    condition: check_session_exists.false
    inputs:
      error: true
      code: "SESSION_NOT_FOUND"
      message: "Session not found"
      session_id: "@outputs('parse_input')?['session_id']"
      suggestion: "Create a new session or verify the session ID"
    run_after: check_session_exists

  # Step 11: Return response
  - id: return_response
    type: Response
    name: Return Response
    inputs:
      statusCode: "@if(outputs('check_session_exists'), 200, 404)"
      headers:
        Content-Type: application/json
      body: "@coalesce(outputs('build_response'), outputs('build_not_found_response'))"

error_handling:
  on_error:
    - id: return_error
      type: Response
      name: Return Error Response
      inputs:
        statusCode: 500
        headers:
          Content-Type: application/json
        body:
          error: true
          code: "INTERNAL_ERROR"
          message: "Failed to retrieve session state"
          session_id: "@outputs('parse_input')?['session_id']"
