# CalculateNBI Power Automate Flow Definition
# Version: 1.0.0
# Agent: SPO (Supply Path Optimization)
# Description: Calculates Net Benefit Index for supply path optimization decisions

name: CalculateNBI
description: >
  HTTP-triggered flow that calculates the Net Benefit Index (NBI) for
  evaluating supply path changes. Balances fee savings against effectiveness
  impact with campaign-type-specific weighting.

trigger:
  type: HTTP
  method: POST
  schema:
    type: object
    required:
      - session_id
      - request_id
      - current_working_media
      - projected_working_media
      - current_performance
      - projected_performance
    properties:
      session_id:
        type: string
        format: uuid
      request_id:
        type: string
        format: uuid
      current_working_media:
        type: number
        minimum: 0
        maximum: 100
        description: Current working media percentage
      projected_working_media:
        type: number
        minimum: 0
        maximum: 100
        description: Projected working media percentage after change
      current_performance:
        type: number
        minimum: 0
        description: Current performance metric value
      projected_performance:
        type: number
        minimum: 0
        description: Projected performance metric after change
      campaign_type:
        type: string
        enum: [awareness, consideration, conversion]
        default: consideration
      metric_type:
        type: string
        enum: [ctr, cvr, cpm, roas, viewability]
        default: cvr

environment_variables:
  EAP_DATAVERSE_URL:
    description: EAP Dataverse environment URL
    required: true

steps:
  # Step 1: Parse input
  - id: parse_input
    type: Compose
    name: Parse Input
    inputs:
      session_id: "@triggerBody()?['session_id']"
      request_id: "@triggerBody()?['request_id']"
      current_working_media: "@triggerBody()?['current_working_media']"
      projected_working_media: "@triggerBody()?['projected_working_media']"
      current_performance: "@triggerBody()?['current_performance']"
      projected_performance: "@triggerBody()?['projected_performance']"
      campaign_type: "@coalesce(triggerBody()?['campaign_type'], 'consideration')"
      metric_type: "@coalesce(triggerBody()?['metric_type'], 'cvr')"
      start_time: "@utcNow()"

  # Step 2: Calculate fee savings
  - id: calculate_fee_savings
    type: Compose
    name: Calculate Fee Savings
    inputs:
      fee_savings: "@sub(outputs('parse_input')?['projected_working_media'], outputs('parse_input')?['current_working_media'])"
      fee_savings_absolute: "@if(greater(outputs('parse_input')?['projected_working_media'], outputs('parse_input')?['current_working_media']), sub(outputs('parse_input')?['projected_working_media'], outputs('parse_input')?['current_working_media']), 0)"
    run_after: parse_input

  # Step 3: Calculate effectiveness impact
  - id: calculate_effectiveness_impact
    type: Compose
    name: Calculate Effectiveness Impact
    inputs:
      performance_delta: "@sub(outputs('parse_input')?['current_performance'], outputs('parse_input')?['projected_performance'])"
      effectiveness_loss_percent: "@if(equals(outputs('parse_input')?['current_performance'], 0), 0, mul(div(sub(outputs('parse_input')?['current_performance'], outputs('parse_input')?['projected_performance']), outputs('parse_input')?['current_performance']), 100))"
    run_after: parse_input

  # Step 4: Determine campaign weight
  - id: determine_weight
    type: Switch
    name: Determine Campaign Weight
    expression: "@outputs('parse_input')?['campaign_type']"
    cases:
      awareness:
        - id: weight_awareness
          type: Compose
          name: Awareness Weight
          inputs:
            weight: 1.2
            rationale: "Awareness campaigns tolerate higher effectiveness loss for fee savings"
      consideration:
        - id: weight_consideration
          type: Compose
          name: Consideration Weight
          inputs:
            weight: 1.5
            rationale: "Consideration campaigns require balanced trade-off"
      conversion:
        - id: weight_conversion
          type: Compose
          name: Conversion Weight
          inputs:
            weight: 2.0
            rationale: "Conversion campaigns heavily penalize effectiveness loss"
    default:
      - id: weight_default
        type: Compose
        name: Default Weight
        inputs:
          weight: 1.5
          rationale: "Default to consideration-level weighting"
    run_after: calculate_effectiveness_impact

  # Step 5: Calculate NBI
  - id: calculate_nbi
    type: Compose
    name: Calculate Net Benefit Index
    inputs:
      fee_savings: "@outputs('calculate_fee_savings')?['fee_savings']"
      effectiveness_loss: "@outputs('calculate_effectiveness_impact')?['effectiveness_loss_percent']"
      weight: "@coalesce(outputs('weight_awareness')?['weight'], outputs('weight_consideration')?['weight'], outputs('weight_conversion')?['weight'], outputs('weight_default')?['weight'])"
      nbi: "@sub(outputs('calculate_fee_savings')?['fee_savings'], mul(outputs('calculate_effectiveness_impact')?['effectiveness_loss_percent'], coalesce(outputs('weight_awareness')?['weight'], outputs('weight_consideration')?['weight'], outputs('weight_conversion')?['weight'], outputs('weight_default')?['weight'])))"
    run_after: determine_weight

  # Step 6: Determine recommendation
  - id: determine_recommendation
    type: Compose
    name: Determine Recommendation
    inputs:
      nbi: "@outputs('calculate_nbi')?['nbi']"
      recommendation: "@if(greater(outputs('calculate_nbi')?['nbi'], 15), 'STRONGLY_RECOMMEND', if(greater(outputs('calculate_nbi')?['nbi'], 8), 'RECOMMEND_WITH_MONITORING', if(greater(outputs('calculate_nbi')?['nbi'], 3), 'EVALUATE_CASE_BY_CASE', if(greater(outputs('calculate_nbi')?['nbi'], -3), 'NEUTRAL', 'NOT_RECOMMENDED'))))"
      confidence: "@if(greater(outputs('calculate_nbi')?['nbi'], 15), 'HIGH', if(greater(outputs('calculate_nbi')?['nbi'], 8), 'MEDIUM', if(greater(outputs('calculate_nbi')?['nbi'], 3), 'LOW', 'MEDIUM')))"
      action_guidance:
        STRONGLY_RECOMMEND: "Proceed with supply path change. Expected net positive impact."
        RECOMMEND_WITH_MONITORING: "Proceed with change. Implement monitoring for 2 weeks."
        EVALUATE_CASE_BY_CASE: "Review specific inventory sources before proceeding."
        NEUTRAL: "No clear benefit. Consider other optimization priorities."
        NOT_RECOMMENDED: "Do not proceed. Effectiveness loss outweighs fee savings."
    run_after: calculate_nbi

  # Step 7: Generate insights
  - id: generate_insights
    type: Compose
    name: Generate Insights
    inputs:
      primary_insight: "@if(greater(outputs('calculate_fee_savings')?['fee_savings'], 0), concat('Supply path change would improve working media by ', string(outputs('calculate_fee_savings')?['fee_savings']), ' percentage points'), 'Supply path change would not improve working media ratio')"
      trade_off_insight: "@if(greater(outputs('calculate_effectiveness_impact')?['effectiveness_loss_percent'], 0), concat('Expected effectiveness reduction of ', string(outputs('calculate_effectiveness_impact')?['effectiveness_loss_percent']), '% must be weighed against fee savings'), 'No expected effectiveness loss - recommended to proceed')"
      campaign_context: "@concat('For ', outputs('parse_input')?['campaign_type'], ' campaigns, effectiveness weight is ', string(outputs('calculate_nbi')?['weight']), 'x')"
    run_after: determine_recommendation

  # Step 8: Build response
  - id: build_response
    type: Compose
    name: Build Response
    inputs:
      request_id: "@outputs('parse_input')?['request_id']"
      timestamp: "@utcNow()"
      source_agent: "SPO"
      status: "success"
      data:
        nbi: "@outputs('calculate_nbi')?['nbi']"
        fee_savings_pct: "@outputs('calculate_fee_savings')?['fee_savings']"
        effectiveness_loss_pct: "@outputs('calculate_effectiveness_impact')?['effectiveness_loss_percent']"
        campaign_weight: "@outputs('calculate_nbi')?['weight']"
        recommendation: "@outputs('determine_recommendation')?['recommendation']"
        confidence: "@outputs('determine_recommendation')?['confidence']"
        action_guidance: "@outputs('determine_recommendation')?['action_guidance']?[outputs('determine_recommendation')?['recommendation']]"
        inputs_summary:
          current_working_media: "@outputs('parse_input')?['current_working_media']"
          projected_working_media: "@outputs('parse_input')?['projected_working_media']"
          current_performance: "@outputs('parse_input')?['current_performance']"
          projected_performance: "@outputs('parse_input')?['projected_performance']"
          campaign_type: "@outputs('parse_input')?['campaign_type']"
        insights: "@outputs('generate_insights')"
      confidence: "@outputs('determine_recommendation')?['confidence']"
      sources:
        - "CALCULATION"
        - "AGENT_KB"
      recommendations:
        - "@outputs('determine_recommendation')?['action_guidance']?[outputs('determine_recommendation')?['recommendation']]"
        - "Monitor quality metrics for 2 weeks post-implementation"
        - "Document baseline metrics before making changes"
      metadata:
        processing_time_ms: "@div(sub(ticks(utcNow()), ticks(outputs('parse_input')?['start_time'])), 10000)"
        nbi_formula: "NBI = Fee Savings - (Effectiveness Loss × Campaign Weight)"
    run_after: generate_insights

  # Step 9: Return response
  - id: return_response
    type: Response
    name: Return Response
    inputs:
      statusCode: 200
      headers:
        Content-Type: application/json
      body: "@outputs('build_response')"

error_handling:
  on_error:
    - id: return_error
      type: Response
      name: Return Error Response
      inputs:
        statusCode: 500
        headers:
          Content-Type: application/json
        body:
          request_id: "@outputs('parse_input')?['request_id']"
          source_agent: "SPO"
          error: true
          code: "NBI_CALCULATION_ERROR"
          message: "Failed to calculate Net Benefit Index"
