-- MCMAP Generated Documents Table Schema v7.0
-- Databricks Delta Lake Definition
-- Source: DOC agent outputs, SharePoint metadata
--
-- Purpose: Store metadata about documents generated by MCMAP agents
-- for tracking, analytics, and content management. Document content
-- remains in SharePoint; this table stores metadata only.

CREATE TABLE IF NOT EXISTS mcmap.v7.generated_documents (
    -- Primary Key
    document_id STRING NOT NULL COMMENT 'Unique document identifier (UUID)',

    -- Document Identity
    document_name STRING NOT NULL COMMENT 'Document filename',
    document_type STRING NOT NULL COMMENT 'Document type (MEDIA_PLAN, PRESENTATION, BRIEF, RFP, REPORT)',
    document_format STRING NOT NULL COMMENT 'File format (DOCX, PPTX, PDF, XLSX)',

    -- Version Control
    version_number INT DEFAULT 1 COMMENT 'Document version number',
    is_latest_version BOOLEAN DEFAULT TRUE COMMENT 'Whether this is the current version',
    previous_version_id STRING COMMENT 'Previous version document ID',

    -- Storage Location
    storage_type STRING NOT NULL COMMENT 'Storage backend (SHAREPOINT, ONEDRIVE, DATABRICKS_VOLUMES)',
    storage_path STRING NOT NULL COMMENT 'Full path to document',
    storage_url STRING COMMENT 'Web-accessible URL',

    -- Size and Content
    file_size_bytes BIGINT COMMENT 'File size in bytes',
    page_count INT COMMENT 'Number of pages (if applicable)',
    word_count INT COMMENT 'Word count (if applicable)',

    -- Generation Context
    session_id STRING COMMENT 'Session that generated the document',
    generating_agent STRING NOT NULL COMMENT 'Agent that created document (DOC, PRF, ANL)',
    generation_trigger STRING COMMENT 'What triggered generation (USER_REQUEST, WORKFLOW_GATE, AUTOMATED)',

    -- Content Summary (for search/analytics)
    content_summary STRING COMMENT 'AI-generated summary of document content',
    key_topics ARRAY<STRING> COMMENT 'Key topics/themes in document',

    -- Client Context
    client_name STRING COMMENT 'Client name (if applicable)',
    campaign_name STRING COMMENT 'Campaign name (if applicable)',
    industry STRING COMMENT 'Client industry',

    -- Plan Context (extracted if media plan)
    total_budget DECIMAL(18,2) COMMENT 'Total budget in document',
    currency STRING COMMENT 'Budget currency',
    campaign_start DATE COMMENT 'Campaign start date',
    campaign_end DATE COMMENT 'Campaign end date',
    channels_included ARRAY<STRING> COMMENT 'Media channels in plan',

    -- Access Control
    owner_user_id STRING COMMENT 'Document owner user ID',
    access_level STRING COMMENT 'Access restriction level (PUBLIC, INTERNAL, RESTRICTED)',
    access_groups ARRAY<STRING> COMMENT 'Groups with access',

    -- Timestamps
    created_at TIMESTAMP NOT NULL COMMENT 'When document was created',
    modified_at TIMESTAMP COMMENT 'Last modification timestamp',
    accessed_at TIMESTAMP COMMENT 'Last access timestamp',
    expires_at TIMESTAMP COMMENT 'Document expiration date (if applicable)',

    -- Metadata
    _ingested_at TIMESTAMP NOT NULL COMMENT 'Databricks ingestion timestamp',
    _batch_id STRING COMMENT 'Export batch identifier'
)
USING DELTA
PARTITIONED BY (document_type, date(created_at))
COMMENT 'MCMAP generated document metadata catalog'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.deletedFileRetentionDuration' = 'interval 30 days',
    'delta.logRetentionDuration' = 'interval 30 days'
);

-- Create indexes for common queries
CREATE BLOOM FILTER INDEX IF NOT EXISTS idx_docs_session
ON mcmap.v7.generated_documents (session_id);

CREATE BLOOM FILTER INDEX IF NOT EXISTS idx_docs_client
ON mcmap.v7.generated_documents (client_name);

CREATE BLOOM FILTER INDEX IF NOT EXISTS idx_docs_owner
ON mcmap.v7.generated_documents (owner_user_id);

-- Grant permissions
GRANT SELECT ON mcmap.v7.generated_documents TO `mcmap-analysts`;
GRANT INSERT, SELECT, UPDATE ON mcmap.v7.generated_documents TO `mcmap-service`;
